// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_Indicate_End_of_Every_ShortFrame_Length_Samples.v
// Created: 2024-01-10 13:49:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_Indicate_End_of_Every_ShortFrame_Length_Samples
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/Interleaver/DVB-S2 HDL Interleaver/RAM Address Generator/Generate 
// and Add Read Base Address/Indicate End of Every ShortFrame Length Sample
// Hierarchy Level: 7
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_Indicate_End_of_Every_ShortFrame_Length_Samples
          (readAddr,
           endIndicate);


  input   [16:0] readAddr;  // ufix17
  output  endIndicate;


  wire Compare_To_Constant_out1;
  wire Compare_To_Constant1_out1;
  wire Compare_To_Constant2_out1;
  wire Compare_To_Constant3_out1;
  wire Logical_Operator1_out1;


  assign Compare_To_Constant_out1 = readAddr == 17'b00011111101000111;



  assign Compare_To_Constant1_out1 = readAddr == 17'b00111111010001111;



  assign Compare_To_Constant2_out1 = readAddr == 17'b01011110111010111;



  assign Compare_To_Constant3_out1 = readAddr == 17'b01111110100011111;



  assign Logical_Operator1_out1 = Compare_To_Constant3_out1 | (Compare_To_Constant2_out1 | (Compare_To_Constant_out1 | Compare_To_Constant1_out1));



  assign endIndicate = Logical_Operator1_out1;

endmodule  // dvbs2hdlTransmitterCore_Indicate_End_of_Every_ShortFrame_Length_Samples

