// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_DVB_S2_Tx.v
// Created: 2024-01-10 13:49:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_DVB_S2_Tx
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx
// Hierarchy Level: 2
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_DVB_S2_Tx
          (clk,
           reset,
           enb,
           enb_1_8_0,
           enb_1_16_1,
           enb_1_8_1,
           enb_1_16_0,
           enb_1_2_0,
           enb_1_2_1,
           pktBitsIn,
           pktStartIn,
           pktEndIn,
           pktValidIn,
           frameStartIn,
           frameEndIn,
           TSorGS,
           DFL,
           UPL,
           SYNC,
           pMODCOD,
           pFECFrame,
           dataOut_re,
           dataOut_im,
           validOut,
           flag,
           nextFrame);


  input   clk;
  input   reset;
  input   enb;
  input   enb_1_8_0;
  input   enb_1_16_1;
  input   enb_1_8_1;
  input   enb_1_16_0;
  input   enb_1_2_0;
  input   enb_1_2_1;
  input   pktBitsIn;
  input   pktStartIn;
  input   pktEndIn;
  input   pktValidIn;
  input   frameStartIn;
  input   frameEndIn;
  input   [1:0] TSorGS;  // ufix2
  input   [15:0] DFL;  // uint16
  input   [15:0] UPL;  // uint16
  input   [7:0] SYNC;  // uint8
  input   [4:0] pMODCOD;  // ufix5
  input   pFECFrame;
  output  signed [17:0] dataOut_re;  // sfix18_En14
  output  signed [17:0] dataOut_im;  // sfix18_En14
  output  validOut;
  output  [1:0] flag;  // ufix2
  output  nextFrame;


  wire BB_Frame_Generator_out1;
  wire BB_Frame_Generator_out2;
  wire BB_Frame_Generator_out3;
  wire BB_Frame_Generator_out4;
  wire [4:0] BB_Frame_Generator_out5;  // ufix5
  wire BB_Frame_Generator_out6;
  wire MODCOD_Source_Coder_out1;
  wire MODCOD_Source_Coder_out2;
  wire MODCOD_Source_Coder_out3;
  wire MODCOD_Source_Coder_out4;
  wire [1:0] MODCOD_Source_Coder_out5;  // ufix2
  wire [3:0] MODCOD_Source_Coder_out6;  // ufix4
  wire MODCOD_Source_Coder_out7;
  wire [4:0] MODCOD_Source_Coder_out8;  // ufix5
  wire FEC_Encoder_out1;
  wire FEC_Encoder_out2;
  wire FEC_Encoder_out3;
  wire [1:0] FEC_Encoder_out4;  // ufix2
  wire [3:0] FEC_Encoder_out5;  // ufix4
  wire FEC_Encoder_out6;
  wire [4:0] FEC_Encoder_out7;  // ufix5
  wire Interleaver_out1;
  wire Interleaver_out2;
  wire Interleaver_out3;
  wire Interleaver_out4;
  wire Interleaver_out5;
  wire [3:0] Interleaver_out6;  // ufix4
  wire [1:0] Interleaver_out7;  // ufix2
  wire [4:0] Interleaver_out8;  // ufix5
  wire ready;
  wire signed [17:0] Symbol_Modulator_out1_re;  // sfix18_En16
  wire signed [17:0] Symbol_Modulator_out1_im;  // sfix18_En16
  wire Symbol_Modulator_out2;
  wire Symbol_Modulator_out3;
  wire Symbol_Modulator_out4;
  wire [1:0] Symbol_Modulator_out5;  // ufix2
  wire Symbol_Modulator_out7;
  wire [4:0] Symbol_Modulator_out8;  // ufix5
  wire signed [17:0] PL_Frame_Generator_out1_re;  // sfix18_En16
  wire signed [17:0] PL_Frame_Generator_out1_im;  // sfix18_En16
  wire PL_Frame_Generator_out2;
  wire PL_Frame_Generator_out3;
  wire PL_Frame_Generator_out4;
  wire signed [17:0] RRC_Transmit_Filter_out1_re;  // sfix18_En14
  wire signed [17:0] RRC_Transmit_Filter_out1_im;  // sfix18_En14
  wire RRC_Transmit_Filter_out2;
  wire [1:0] Bit_Concat_out1;  // ufix2
  reg  Delay_out1;
  wire Logical_Operator_out1;
  wire Logical_Operator1_out1;
  wire Unit_Delay_Enabled_Resettable_Synchronous_iv;
  reg  Unit_Delay_Enabled_Resettable_Synchronous_out1;
  wire Unit_Delay_Enabled_Resettable_Synchronous_ectrl;
  wire Unit_Delay_Enabled_Resettable_Synchronous_toDelay;


  dvbs2hdlTransmitterCore_BB_Frame_Generator u_BB_Frame_Generator (.clk(clk),
                                                                   .reset(reset),
                                                                   .enb(enb),
                                                                   .pktBitsIn(pktBitsIn),
                                                                   .pktStartIn(pktStartIn),
                                                                   .pktEndIn(pktEndIn),
                                                                   .pktValidIn(pktValidIn),
                                                                   .frameStartIn(frameStartIn),
                                                                   .frameEndIn(frameEndIn),
                                                                   .TSorGS(TSorGS),  // ufix2
                                                                   .DFL(DFL),  // uint16
                                                                   .UPL(UPL),  // uint16
                                                                   .SYNC(SYNC),  // uint8
                                                                   .pMODCOD(pMODCOD),  // ufix5
                                                                   .pFECFrame(pFECFrame),
                                                                   .dataOut(BB_Frame_Generator_out1),
                                                                   .startOut(BB_Frame_Generator_out2),
                                                                   .endOut(BB_Frame_Generator_out3),
                                                                   .validOut(BB_Frame_Generator_out4),
                                                                   .MODCOD(BB_Frame_Generator_out5),  // ufix5
                                                                   .FECFrame(BB_Frame_Generator_out6)
                                                                   );

  dvbs2hdlTransmitterCore_MODCOD_Source_Coder u_MODCOD_Source_Coder (.clk(clk),
                                                                     .reset(reset),
                                                                     .enb(enb),
                                                                     .dataIn(BB_Frame_Generator_out1),
                                                                     .startIn(BB_Frame_Generator_out2),
                                                                     .endIn(BB_Frame_Generator_out3),
                                                                     .validIn(BB_Frame_Generator_out4),
                                                                     .MODCODIn(BB_Frame_Generator_out5),  // ufix5
                                                                     .FECFrameIn(BB_Frame_Generator_out6),
                                                                     .dataOut(MODCOD_Source_Coder_out1),
                                                                     .startOut(MODCOD_Source_Coder_out2),
                                                                     .endOut(MODCOD_Source_Coder_out3),
                                                                     .validOut(MODCOD_Source_Coder_out4),
                                                                     .modIdx(MODCOD_Source_Coder_out5),  // ufix2
                                                                     .codeRateIdx(MODCOD_Source_Coder_out6),  // ufix4
                                                                     .FECFrame(MODCOD_Source_Coder_out7),
                                                                     .MODCOD(MODCOD_Source_Coder_out8)  // ufix5
                                                                     );

  dvbs2hdlTransmitterCore_FEC_Encoder u_FEC_Encoder (.clk(clk),
                                                     .reset(reset),
                                                     .enb(enb),
                                                     .dataIn(MODCOD_Source_Coder_out1),
                                                     .startIn(MODCOD_Source_Coder_out2),
                                                     .endIn(MODCOD_Source_Coder_out3),
                                                     .validIn(MODCOD_Source_Coder_out4),
                                                     .modIdxIn(MODCOD_Source_Coder_out5),  // ufix2
                                                     .codeRateIdxIn(MODCOD_Source_Coder_out6),  // ufix4
                                                     .FECFrameIn(MODCOD_Source_Coder_out7),
                                                     .MODCODIn(MODCOD_Source_Coder_out8),  // ufix5
                                                     .dataOut(FEC_Encoder_out1),
                                                     .validOut(FEC_Encoder_out2),
                                                     .startOut(FEC_Encoder_out3),
                                                     .modOut(FEC_Encoder_out4),  // ufix2
                                                     .codOut(FEC_Encoder_out5),  // ufix4
                                                     .fecOut(FEC_Encoder_out6),
                                                     .MODCOD(FEC_Encoder_out7)  // ufix5
                                                     );

  dvbs2hdlTransmitterCore_Interleaver u_Interleaver (.clk(clk),
                                                     .reset(reset),
                                                     .enb(enb),
                                                     .dataIn(FEC_Encoder_out1),
                                                     .validIn(FEC_Encoder_out2),
                                                     .paramValid(FEC_Encoder_out3),
                                                     .modIdxIn(FEC_Encoder_out4),  // ufix2
                                                     .codIdxIn(FEC_Encoder_out5),  // ufix4
                                                     .fecframeIn(FEC_Encoder_out6),
                                                     .MODCODIn(FEC_Encoder_out7),  // ufix5
                                                     .dataOut(Interleaver_out1),
                                                     .startOut(Interleaver_out2),
                                                     .endOut(Interleaver_out3),
                                                     .validOut(Interleaver_out4),
                                                     .FECFrame(Interleaver_out5),
                                                     .codIdx(Interleaver_out6),  // ufix4
                                                     .modIdx(Interleaver_out7),  // ufix2
                                                     .MODCOD(Interleaver_out8),  // ufix5
                                                     .ready(ready)
                                                     );

  dvbs2hdlTransmitterCore_Symbol_Modulator u_Symbol_Modulator (.clk(clk),
                                                               .reset(reset),
                                                               .enb(enb),
                                                               .dataIn(Interleaver_out1),
                                                               .startIn(Interleaver_out2),
                                                               .endIn(Interleaver_out3),
                                                               .validIn(Interleaver_out4),
                                                               .FECFrame(Interleaver_out5),
                                                               .codIdx(Interleaver_out6),  // ufix4
                                                               .modIdx(Interleaver_out7),  // ufix2
                                                               .MODCOD(Interleaver_out8),  // ufix5
                                                               .dataOut_re(Symbol_Modulator_out1_re),  // sfix18_En16
                                                               .dataOut_im(Symbol_Modulator_out1_im),  // sfix18_En16
                                                               .startOut(Symbol_Modulator_out2),
                                                               .endOut(Symbol_Modulator_out3),
                                                               .validOut(Symbol_Modulator_out4),
                                                               .modIdxOut(Symbol_Modulator_out5),  // ufix2
                                                               .FECFrameOut(Symbol_Modulator_out7),
                                                               .MODCODOut(Symbol_Modulator_out8)  // ufix5
                                                               );

  dvbs2hdlTransmitterCore_PL_Frame_Generator u_PL_Frame_Generator (.clk(clk),
                                                                   .reset(reset),
                                                                   .enb(enb),
                                                                   .enb_1_8_0(enb_1_8_0),
                                                                   .enb_1_16_1(enb_1_16_1),
                                                                   .enb_1_8_1(enb_1_8_1),
                                                                   .enb_1_16_0(enb_1_16_0),
                                                                   .dataIn_re(Symbol_Modulator_out1_re),  // sfix18_En16
                                                                   .dataIn_im(Symbol_Modulator_out1_im),  // sfix18_En16
                                                                   .startIn(Symbol_Modulator_out2),
                                                                   .endIn(Symbol_Modulator_out3),
                                                                   .validIn(Symbol_Modulator_out4),
                                                                   .modIdxIn(Symbol_Modulator_out5),  // ufix2
                                                                   .fecframeIn(Symbol_Modulator_out7),
                                                                   .modcod(Symbol_Modulator_out8),  // ufix5
                                                                   .dataOut_re(PL_Frame_Generator_out1_re),  // sfix18_En16
                                                                   .dataOut_im(PL_Frame_Generator_out1_im),  // sfix18_En16
                                                                   .validOut(PL_Frame_Generator_out2),
                                                                   .dummyHeaderEnd(PL_Frame_Generator_out3),
                                                                   .PLHeaderEnd(PL_Frame_Generator_out4)
                                                                   );

  dvbs2hdlTransmitterCore_RRC_Transmit_Filter u_RRC_Transmit_Filter (.clk(clk),
                                                                     .reset(reset),
                                                                     .enb_1_8_1(enb_1_8_1),
                                                                     .enb_1_2_0(enb_1_2_0),
                                                                     .enb_1_2_1(enb_1_2_1),
                                                                     .dataIn_re(PL_Frame_Generator_out1_re),  // sfix18_En16
                                                                     .dataIn_im(PL_Frame_Generator_out1_im),  // sfix18_En16
                                                                     .validIn(PL_Frame_Generator_out2),
                                                                     .dataOut_re(RRC_Transmit_Filter_out1_re),  // sfix18_En14
                                                                     .dataOut_im(RRC_Transmit_Filter_out1_im),  // sfix18_En14
                                                                     .validOut(RRC_Transmit_Filter_out2)
                                                                     );

  assign dataOut_re = RRC_Transmit_Filter_out1_re;

  assign dataOut_im = RRC_Transmit_Filter_out1_im;

  assign validOut = RRC_Transmit_Filter_out2;

  assign Bit_Concat_out1 = {PL_Frame_Generator_out3, PL_Frame_Generator_out4};



  assign flag = Bit_Concat_out1;

  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1 <= ready;
        end
      end
    end



  assign Logical_Operator_out1 =  ~ Delay_out1;



  assign Logical_Operator1_out1 = ready & Logical_Operator_out1;



  assign Unit_Delay_Enabled_Resettable_Synchronous_iv = 1'b0;



  assign Unit_Delay_Enabled_Resettable_Synchronous_ectrl = (Logical_Operator1_out1 == 1'b0 ? Unit_Delay_Enabled_Resettable_Synchronous_out1 :
              Logical_Operator1_out1);



  assign Unit_Delay_Enabled_Resettable_Synchronous_toDelay = (frameStartIn == 1'b0 ? Unit_Delay_Enabled_Resettable_Synchronous_ectrl :
              Unit_Delay_Enabled_Resettable_Synchronous_iv);



  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Resettable_Synchronous_lowered_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Resettable_Synchronous_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Unit_Delay_Enabled_Resettable_Synchronous_out1 <= Unit_Delay_Enabled_Resettable_Synchronous_toDelay;
        end
      end
    end



  assign nextFrame = Unit_Delay_Enabled_Resettable_Synchronous_out1;

endmodule  // dvbs2hdlTransmitterCore_DVB_S2_Tx

