// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_Single_RAM_Using_Two_RAMs.v
// Created: 2024-01-10 13:49:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_Single_RAM_Using_Two_RAMs
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/Interleaver/DVB-S2 HDL Interleaver/RAM/Single RAM Using Two RAMs
// Hierarchy Level: 6
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_Single_RAM_Using_Two_RAMs
          (clk,
           reset,
           enb,
           wr_din,
           wr_addr,
           wr_en,
           rd_addr,
           rd_dout);


  input   clk;
  input   reset;
  input   enb;
  input   wr_din;
  input   [16:0] wr_addr;  // ufix17
  input   wr_en;
  input   [16:0] rd_addr;  // ufix17
  output  rd_dout;


  wire Extract_Bits3_out1;  // ufix1
  reg  Delay_out1;  // ufix1
  wire [15:0] Extract_Bits_out1;  // uint16
  wire Extract_Bits1_out1;  // ufix1
  wire Logical_Operator1_out1;
  wire Logical_Operator3_out1;
  wire [15:0] Extract_Bits2_out1;  // uint16
  wire Simple_Dual_Port_RAM_out1;
  wire Logical_Operator2_out1;
  wire Simple_Dual_Port_RAM1_out1;
  wire Multiport_Switch_out1;


  assign Extract_Bits3_out1 = rd_addr[16];



  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1 <= Extract_Bits3_out1;
        end
      end
    end



  assign Extract_Bits_out1 = wr_addr[15:0];



  assign Extract_Bits1_out1 = wr_addr[16];



  assign Logical_Operator1_out1 =  ~ Extract_Bits1_out1;



  assign Logical_Operator3_out1 = Logical_Operator1_out1 & wr_en;



  assign Extract_Bits2_out1 = rd_addr[15:0];



  dvbs2hdlTransmitterCore_SimpleDualPortRAM_singlebit #(.AddrWidth(16),
                                                        .DataWidth(1)
                                                        )
                                                      u_Simple_Dual_Port_RAM (.clk(clk),
                                                                              .enb(enb),
                                                                              .wr_din(wr_din),
                                                                              .wr_addr(Extract_Bits_out1),
                                                                              .wr_en(Logical_Operator3_out1),
                                                                              .rd_addr(Extract_Bits2_out1),
                                                                              .dout(Simple_Dual_Port_RAM_out1)
                                                                              );

  assign Logical_Operator2_out1 = Extract_Bits1_out1 & wr_en;



  dvbs2hdlTransmitterCore_SimpleDualPortRAM_singlebit #(.AddrWidth(16),
                                                        .DataWidth(1)
                                                        )
                                                      u_Simple_Dual_Port_RAM1 (.clk(clk),
                                                                               .enb(enb),
                                                                               .wr_din(wr_din),
                                                                               .wr_addr(Extract_Bits_out1),
                                                                               .wr_en(Logical_Operator2_out1),
                                                                               .rd_addr(Extract_Bits2_out1),
                                                                               .dout(Simple_Dual_Port_RAM1_out1)
                                                                               );

  assign Multiport_Switch_out1 = (Delay_out1 == 1'b0 ? Simple_Dual_Port_RAM_out1 :
              Simple_Dual_Port_RAM1_out1);



  assign rd_dout = Multiport_Switch_out1;

endmodule  // dvbs2hdlTransmitterCore_Single_RAM_Using_Two_RAMs

