// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_Indexing.v
// Created: 2024-01-10 13:49:57
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_Indexing
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/FEC Encoder/DVB-S2 LDPC Encoder/Indexing
// Hierarchy Level: 5
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_Indexing
          (in_data_0,
           in_data_1,
           in_data_2,
           in_data_3,
           in_data_4,
           in_data_5,
           in_data_6,
           in_data_7,
           in_data_8,
           in_data_9,
           in_data_10,
           in_data_11,
           in_data_12,
           in_data_13,
           in_data_14,
           in_data_15,
           in_data_16,
           in_data_17,
           in_data_18,
           in_data_19,
           in_data_20,
           in_data_21,
           in_data_22,
           in_data_23,
           in_data_24,
           in_data_25,
           in_data_26,
           in_data_27,
           in_data_28,
           in_data_29,
           in_data_30,
           in_data_31,
           in_data_32,
           in_data_33,
           in_data_34,
           in_data_35,
           in_data_36,
           in_data_37,
           in_data_38,
           in_data_39,
           in_data_40,
           in_data_41,
           in_data_42,
           in_data_43,
           in_data_44,
           in_data_45,
           in_data_46,
           in_data_47,
           in_data_48,
           in_data_49,
           in_data_50,
           in_data_51,
           in_data_52,
           in_data_53,
           in_data_54,
           in_data_55,
           in_data_56,
           in_data_57,
           in_data_58,
           in_data_59,
           in_data_60,
           in_data_61,
           in_data_62,
           in_data_63,
           in_data_64,
           in_data_65,
           in_data_66,
           in_data_67,
           in_data_68,
           in_data_69,
           in_data_70,
           in_data_71,
           in_data_72,
           in_data_73,
           in_data_74,
           in_data_75,
           in_data_76,
           in_data_77,
           in_data_78,
           in_data_79,
           in_data_80,
           in_data_81,
           in_data_82,
           in_data_83,
           in_data_84,
           in_data_85,
           in_data_86,
           in_data_87,
           in_data_88,
           in_data_89,
           in_data_90,
           in_data_91,
           in_data_92,
           in_data_93,
           in_data_94,
           in_data_95,
           in_data_96,
           in_data_97,
           in_data_98,
           in_data_99,
           in_data_100,
           in_data_101,
           in_data_102,
           in_data_103,
           in_data_104,
           in_data_105,
           in_data_106,
           in_data_107,
           in_data_108,
           in_data_109,
           in_data_110,
           in_data_111,
           in_data_112,
           in_data_113,
           in_data_114,
           in_data_115,
           in_data_116,
           in_data_117,
           in_data_118,
           in_data_119,
           in_data_120,
           in_data_121,
           in_data_122,
           in_data_123,
           in_data_124,
           in_data_125,
           in_data_126,
           in_data_127,
           in_data_128,
           in_data_129,
           in_data_130,
           in_data_131,
           in_data_132,
           in_data_133,
           in_data_134,
           in_data_135,
           in_data_136,
           in_data_137,
           in_data_138,
           in_data_139,
           in_data_140,
           in_data_141,
           in_data_142,
           in_data_143,
           in_data_144,
           in_data_145,
           in_data_146,
           in_data_147,
           in_data_148,
           in_data_149,
           in_data_150,
           in_data_151,
           in_data_152,
           in_data_153,
           in_data_154,
           in_data_155,
           in_data_156,
           in_data_157,
           in_data_158,
           in_data_159,
           in_data_160,
           in_data_161,
           in_data_162,
           in_data_163,
           in_data_164,
           in_data_165,
           in_data_166,
           in_data_167,
           in_data_168,
           in_data_169,
           in_data_170,
           in_data_171,
           in_data_172,
           in_data_173,
           in_data_174,
           in_data_175,
           in_data_176,
           in_data_177,
           in_data_178,
           in_data_179,
           in_data_180,
           in_data_181,
           in_data_182,
           in_data_183,
           in_data_184,
           in_data_185,
           in_data_186,
           in_data_187,
           in_data_188,
           in_data_189,
           in_data_190,
           in_data_191,
           in_data_192,
           in_data_193,
           in_data_194,
           in_data_195,
           in_data_196,
           in_data_197,
           in_data_198,
           in_data_199,
           in_data_200,
           in_data_201,
           in_data_202,
           in_data_203,
           in_data_204,
           in_data_205,
           in_data_206,
           in_data_207,
           in_data_208,
           in_data_209,
           in_data_210,
           in_data_211,
           in_data_212,
           in_data_213,
           in_data_214,
           in_data_215,
           in_data_216,
           in_data_217,
           in_data_218,
           in_data_219,
           in_data_220,
           in_data_221,
           in_data_222,
           in_data_223,
           in_data_224,
           in_data_225,
           in_data_226,
           in_data_227,
           in_data_228,
           in_data_229,
           in_data_230,
           in_data_231,
           in_data_232,
           in_data_233,
           in_data_234,
           in_data_235,
           in_data_236,
           in_data_237,
           in_data_238,
           in_data_239,
           in_data_240,
           in_data_241,
           in_data_242,
           in_data_243,
           in_data_244,
           in_data_245,
           in_data_246,
           in_data_247,
           in_data_248,
           in_data_249,
           in_data_250,
           in_data_251,
           in_data_252,
           in_data_253,
           in_data_254,
           in_data_255,
           in_data_256,
           in_data_257,
           in_data_258,
           in_data_259,
           in_data_260,
           in_data_261,
           in_data_262,
           in_data_263,
           in_data_264,
           in_data_265,
           in_data_266,
           in_data_267,
           in_data_268,
           in_data_269,
           in_data_270,
           in_data_271,
           in_data_272,
           in_data_273,
           in_data_274,
           in_data_275,
           in_data_276,
           in_data_277,
           in_data_278,
           in_data_279,
           in_data_280,
           in_data_281,
           in_data_282,
           in_data_283,
           in_data_284,
           in_data_285,
           in_data_286,
           in_data_287,
           in_data_288,
           in_data_289,
           in_data_290,
           in_data_291,
           in_data_292,
           in_data_293,
           in_data_294,
           in_data_295,
           in_data_296,
           in_data_297,
           in_data_298,
           in_data_299,
           in_data_300,
           in_data_301,
           in_data_302,
           in_data_303,
           in_data_304,
           in_data_305,
           in_data_306,
           in_data_307,
           in_data_308,
           in_data_309,
           in_data_310,
           in_data_311,
           in_data_312,
           in_data_313,
           in_data_314,
           in_data_315,
           in_data_316,
           in_data_317,
           in_data_318,
           in_data_319,
           in_data_320,
           in_data_321,
           in_data_322,
           in_data_323,
           in_data_324,
           in_data_325,
           in_data_326,
           in_data_327,
           in_data_328,
           in_data_329,
           in_data_330,
           in_data_331,
           in_data_332,
           in_data_333,
           in_data_334,
           in_data_335,
           in_data_336,
           in_data_337,
           in_data_338,
           in_data_339,
           in_data_340,
           in_data_341,
           in_data_342,
           in_data_343,
           in_data_344,
           in_data_345,
           in_data_346,
           in_data_347,
           in_data_348,
           in_data_349,
           in_data_350,
           in_data_351,
           in_data_352,
           in_data_353,
           in_data_354,
           in_data_355,
           in_data_356,
           in_data_357,
           in_data_358,
           in_data_359,
           i_index,
           par_data_0,
           par_data_1,
           par_data_2,
           par_data_3,
           par_data_4,
           par_data_5,
           par_data_6,
           par_data_7,
           par_data_8,
           par_data_9,
           par_data_10,
           par_data_11,
           par_data_12,
           par_data_13,
           par_data_14,
           par_data_15,
           par_data_16,
           par_data_17,
           par_data_18,
           par_data_19,
           par_data_20,
           par_data_21,
           par_data_22,
           par_data_23,
           par_data_24,
           par_data_25,
           par_data_26,
           par_data_27,
           par_data_28,
           par_data_29,
           par_data_30,
           par_data_31,
           par_data_32,
           par_data_33,
           par_data_34,
           par_data_35,
           par_data_36,
           par_data_37,
           par_data_38,
           par_data_39,
           par_data_40,
           par_data_41,
           par_data_42,
           par_data_43,
           par_data_44,
           par_data_45,
           par_data_46,
           par_data_47,
           par_data_48,
           par_data_49,
           par_data_50,
           par_data_51,
           par_data_52,
           par_data_53,
           par_data_54,
           par_data_55,
           par_data_56,
           par_data_57,
           par_data_58,
           par_data_59,
           par_data_60,
           par_data_61,
           par_data_62,
           par_data_63,
           par_data_64,
           par_data_65,
           par_data_66,
           par_data_67,
           par_data_68,
           par_data_69,
           par_data_70,
           par_data_71,
           par_data_72,
           par_data_73,
           par_data_74,
           par_data_75,
           par_data_76,
           par_data_77,
           par_data_78,
           par_data_79,
           par_data_80,
           par_data_81,
           par_data_82,
           par_data_83,
           par_data_84,
           par_data_85,
           par_data_86,
           par_data_87,
           par_data_88,
           par_data_89,
           par_data_90,
           par_data_91,
           par_data_92,
           par_data_93,
           par_data_94,
           par_data_95,
           par_data_96,
           par_data_97,
           par_data_98,
           par_data_99,
           par_data_100,
           par_data_101,
           par_data_102,
           par_data_103,
           par_data_104,
           par_data_105,
           par_data_106,
           par_data_107,
           par_data_108,
           par_data_109,
           par_data_110,
           par_data_111,
           par_data_112,
           par_data_113,
           par_data_114,
           par_data_115,
           par_data_116,
           par_data_117,
           par_data_118,
           par_data_119,
           par_data_120,
           par_data_121,
           par_data_122,
           par_data_123,
           par_data_124,
           par_data_125,
           par_data_126,
           par_data_127,
           par_data_128,
           par_data_129,
           par_data_130,
           par_data_131,
           par_data_132,
           par_data_133,
           par_data_134,
           par_data_135,
           par_data_136,
           par_data_137,
           par_data_138,
           par_data_139,
           par_data_140,
           par_data_141,
           par_data_142,
           par_data_143,
           par_data_144,
           par_data_145,
           par_data_146,
           par_data_147,
           par_data_148,
           par_data_149,
           par_data_150,
           par_data_151,
           par_data_152,
           par_data_153,
           par_data_154,
           par_data_155,
           par_data_156,
           par_data_157,
           par_data_158,
           par_data_159,
           par_data_160,
           par_data_161,
           par_data_162,
           par_data_163,
           par_data_164,
           par_data_165,
           par_data_166,
           par_data_167,
           par_data_168,
           par_data_169,
           par_data_170,
           par_data_171,
           par_data_172,
           par_data_173,
           par_data_174,
           par_data_175,
           par_data_176,
           par_data_177,
           par_data_178,
           par_data_179,
           par_data_180,
           par_data_181,
           par_data_182,
           par_data_183,
           par_data_184,
           par_data_185,
           par_data_186,
           par_data_187,
           par_data_188,
           par_data_189,
           par_data_190,
           par_data_191,
           par_data_192,
           par_data_193,
           par_data_194,
           par_data_195,
           par_data_196,
           par_data_197,
           par_data_198,
           par_data_199,
           par_data_200,
           par_data_201,
           par_data_202,
           par_data_203,
           par_data_204,
           par_data_205,
           par_data_206,
           par_data_207,
           par_data_208,
           par_data_209,
           par_data_210,
           par_data_211,
           par_data_212,
           par_data_213,
           par_data_214,
           par_data_215,
           par_data_216,
           par_data_217,
           par_data_218,
           par_data_219,
           par_data_220,
           par_data_221,
           par_data_222,
           par_data_223,
           par_data_224,
           par_data_225,
           par_data_226,
           par_data_227,
           par_data_228,
           par_data_229,
           par_data_230,
           par_data_231,
           par_data_232,
           par_data_233,
           par_data_234,
           par_data_235,
           par_data_236,
           par_data_237,
           par_data_238,
           par_data_239,
           par_data_240,
           par_data_241,
           par_data_242,
           par_data_243,
           par_data_244,
           par_data_245,
           par_data_246,
           par_data_247,
           par_data_248,
           par_data_249,
           par_data_250,
           par_data_251,
           par_data_252,
           par_data_253,
           par_data_254,
           par_data_255,
           par_data_256,
           par_data_257,
           par_data_258,
           par_data_259,
           par_data_260,
           par_data_261,
           par_data_262,
           par_data_263,
           par_data_264,
           par_data_265,
           par_data_266,
           par_data_267,
           par_data_268,
           par_data_269,
           par_data_270,
           par_data_271,
           par_data_272,
           par_data_273,
           par_data_274,
           par_data_275,
           par_data_276,
           par_data_277,
           par_data_278,
           par_data_279,
           par_data_280,
           par_data_281,
           par_data_282,
           par_data_283,
           par_data_284,
           par_data_285,
           par_data_286,
           par_data_287,
           par_data_288,
           par_data_289,
           par_data_290,
           par_data_291,
           par_data_292,
           par_data_293,
           par_data_294,
           par_data_295,
           par_data_296,
           par_data_297,
           par_data_298,
           par_data_299,
           par_data_300,
           par_data_301,
           par_data_302,
           par_data_303,
           par_data_304,
           par_data_305,
           par_data_306,
           par_data_307,
           par_data_308,
           par_data_309,
           par_data_310,
           par_data_311,
           par_data_312,
           par_data_313,
           par_data_314,
           par_data_315,
           par_data_316,
           par_data_317,
           par_data_318,
           par_data_319,
           par_data_320,
           par_data_321,
           par_data_322,
           par_data_323,
           par_data_324,
           par_data_325,
           par_data_326,
           par_data_327,
           par_data_328,
           par_data_329,
           par_data_330,
           par_data_331,
           par_data_332,
           par_data_333,
           par_data_334,
           par_data_335,
           par_data_336,
           par_data_337,
           par_data_338,
           par_data_339,
           par_data_340,
           par_data_341,
           par_data_342,
           par_data_343,
           par_data_344,
           par_data_345,
           par_data_346,
           par_data_347,
           par_data_348,
           par_data_349,
           par_data_350,
           par_data_351,
           par_data_352,
           par_data_353,
           par_data_354,
           par_data_355,
           par_data_356,
           par_data_357,
           par_data_358,
           par_data_359,
           p_index,
           parity,
           input_rsvd);


  input   in_data_0;
  input   in_data_1;
  input   in_data_2;
  input   in_data_3;
  input   in_data_4;
  input   in_data_5;
  input   in_data_6;
  input   in_data_7;
  input   in_data_8;
  input   in_data_9;
  input   in_data_10;
  input   in_data_11;
  input   in_data_12;
  input   in_data_13;
  input   in_data_14;
  input   in_data_15;
  input   in_data_16;
  input   in_data_17;
  input   in_data_18;
  input   in_data_19;
  input   in_data_20;
  input   in_data_21;
  input   in_data_22;
  input   in_data_23;
  input   in_data_24;
  input   in_data_25;
  input   in_data_26;
  input   in_data_27;
  input   in_data_28;
  input   in_data_29;
  input   in_data_30;
  input   in_data_31;
  input   in_data_32;
  input   in_data_33;
  input   in_data_34;
  input   in_data_35;
  input   in_data_36;
  input   in_data_37;
  input   in_data_38;
  input   in_data_39;
  input   in_data_40;
  input   in_data_41;
  input   in_data_42;
  input   in_data_43;
  input   in_data_44;
  input   in_data_45;
  input   in_data_46;
  input   in_data_47;
  input   in_data_48;
  input   in_data_49;
  input   in_data_50;
  input   in_data_51;
  input   in_data_52;
  input   in_data_53;
  input   in_data_54;
  input   in_data_55;
  input   in_data_56;
  input   in_data_57;
  input   in_data_58;
  input   in_data_59;
  input   in_data_60;
  input   in_data_61;
  input   in_data_62;
  input   in_data_63;
  input   in_data_64;
  input   in_data_65;
  input   in_data_66;
  input   in_data_67;
  input   in_data_68;
  input   in_data_69;
  input   in_data_70;
  input   in_data_71;
  input   in_data_72;
  input   in_data_73;
  input   in_data_74;
  input   in_data_75;
  input   in_data_76;
  input   in_data_77;
  input   in_data_78;
  input   in_data_79;
  input   in_data_80;
  input   in_data_81;
  input   in_data_82;
  input   in_data_83;
  input   in_data_84;
  input   in_data_85;
  input   in_data_86;
  input   in_data_87;
  input   in_data_88;
  input   in_data_89;
  input   in_data_90;
  input   in_data_91;
  input   in_data_92;
  input   in_data_93;
  input   in_data_94;
  input   in_data_95;
  input   in_data_96;
  input   in_data_97;
  input   in_data_98;
  input   in_data_99;
  input   in_data_100;
  input   in_data_101;
  input   in_data_102;
  input   in_data_103;
  input   in_data_104;
  input   in_data_105;
  input   in_data_106;
  input   in_data_107;
  input   in_data_108;
  input   in_data_109;
  input   in_data_110;
  input   in_data_111;
  input   in_data_112;
  input   in_data_113;
  input   in_data_114;
  input   in_data_115;
  input   in_data_116;
  input   in_data_117;
  input   in_data_118;
  input   in_data_119;
  input   in_data_120;
  input   in_data_121;
  input   in_data_122;
  input   in_data_123;
  input   in_data_124;
  input   in_data_125;
  input   in_data_126;
  input   in_data_127;
  input   in_data_128;
  input   in_data_129;
  input   in_data_130;
  input   in_data_131;
  input   in_data_132;
  input   in_data_133;
  input   in_data_134;
  input   in_data_135;
  input   in_data_136;
  input   in_data_137;
  input   in_data_138;
  input   in_data_139;
  input   in_data_140;
  input   in_data_141;
  input   in_data_142;
  input   in_data_143;
  input   in_data_144;
  input   in_data_145;
  input   in_data_146;
  input   in_data_147;
  input   in_data_148;
  input   in_data_149;
  input   in_data_150;
  input   in_data_151;
  input   in_data_152;
  input   in_data_153;
  input   in_data_154;
  input   in_data_155;
  input   in_data_156;
  input   in_data_157;
  input   in_data_158;
  input   in_data_159;
  input   in_data_160;
  input   in_data_161;
  input   in_data_162;
  input   in_data_163;
  input   in_data_164;
  input   in_data_165;
  input   in_data_166;
  input   in_data_167;
  input   in_data_168;
  input   in_data_169;
  input   in_data_170;
  input   in_data_171;
  input   in_data_172;
  input   in_data_173;
  input   in_data_174;
  input   in_data_175;
  input   in_data_176;
  input   in_data_177;
  input   in_data_178;
  input   in_data_179;
  input   in_data_180;
  input   in_data_181;
  input   in_data_182;
  input   in_data_183;
  input   in_data_184;
  input   in_data_185;
  input   in_data_186;
  input   in_data_187;
  input   in_data_188;
  input   in_data_189;
  input   in_data_190;
  input   in_data_191;
  input   in_data_192;
  input   in_data_193;
  input   in_data_194;
  input   in_data_195;
  input   in_data_196;
  input   in_data_197;
  input   in_data_198;
  input   in_data_199;
  input   in_data_200;
  input   in_data_201;
  input   in_data_202;
  input   in_data_203;
  input   in_data_204;
  input   in_data_205;
  input   in_data_206;
  input   in_data_207;
  input   in_data_208;
  input   in_data_209;
  input   in_data_210;
  input   in_data_211;
  input   in_data_212;
  input   in_data_213;
  input   in_data_214;
  input   in_data_215;
  input   in_data_216;
  input   in_data_217;
  input   in_data_218;
  input   in_data_219;
  input   in_data_220;
  input   in_data_221;
  input   in_data_222;
  input   in_data_223;
  input   in_data_224;
  input   in_data_225;
  input   in_data_226;
  input   in_data_227;
  input   in_data_228;
  input   in_data_229;
  input   in_data_230;
  input   in_data_231;
  input   in_data_232;
  input   in_data_233;
  input   in_data_234;
  input   in_data_235;
  input   in_data_236;
  input   in_data_237;
  input   in_data_238;
  input   in_data_239;
  input   in_data_240;
  input   in_data_241;
  input   in_data_242;
  input   in_data_243;
  input   in_data_244;
  input   in_data_245;
  input   in_data_246;
  input   in_data_247;
  input   in_data_248;
  input   in_data_249;
  input   in_data_250;
  input   in_data_251;
  input   in_data_252;
  input   in_data_253;
  input   in_data_254;
  input   in_data_255;
  input   in_data_256;
  input   in_data_257;
  input   in_data_258;
  input   in_data_259;
  input   in_data_260;
  input   in_data_261;
  input   in_data_262;
  input   in_data_263;
  input   in_data_264;
  input   in_data_265;
  input   in_data_266;
  input   in_data_267;
  input   in_data_268;
  input   in_data_269;
  input   in_data_270;
  input   in_data_271;
  input   in_data_272;
  input   in_data_273;
  input   in_data_274;
  input   in_data_275;
  input   in_data_276;
  input   in_data_277;
  input   in_data_278;
  input   in_data_279;
  input   in_data_280;
  input   in_data_281;
  input   in_data_282;
  input   in_data_283;
  input   in_data_284;
  input   in_data_285;
  input   in_data_286;
  input   in_data_287;
  input   in_data_288;
  input   in_data_289;
  input   in_data_290;
  input   in_data_291;
  input   in_data_292;
  input   in_data_293;
  input   in_data_294;
  input   in_data_295;
  input   in_data_296;
  input   in_data_297;
  input   in_data_298;
  input   in_data_299;
  input   in_data_300;
  input   in_data_301;
  input   in_data_302;
  input   in_data_303;
  input   in_data_304;
  input   in_data_305;
  input   in_data_306;
  input   in_data_307;
  input   in_data_308;
  input   in_data_309;
  input   in_data_310;
  input   in_data_311;
  input   in_data_312;
  input   in_data_313;
  input   in_data_314;
  input   in_data_315;
  input   in_data_316;
  input   in_data_317;
  input   in_data_318;
  input   in_data_319;
  input   in_data_320;
  input   in_data_321;
  input   in_data_322;
  input   in_data_323;
  input   in_data_324;
  input   in_data_325;
  input   in_data_326;
  input   in_data_327;
  input   in_data_328;
  input   in_data_329;
  input   in_data_330;
  input   in_data_331;
  input   in_data_332;
  input   in_data_333;
  input   in_data_334;
  input   in_data_335;
  input   in_data_336;
  input   in_data_337;
  input   in_data_338;
  input   in_data_339;
  input   in_data_340;
  input   in_data_341;
  input   in_data_342;
  input   in_data_343;
  input   in_data_344;
  input   in_data_345;
  input   in_data_346;
  input   in_data_347;
  input   in_data_348;
  input   in_data_349;
  input   in_data_350;
  input   in_data_351;
  input   in_data_352;
  input   in_data_353;
  input   in_data_354;
  input   in_data_355;
  input   in_data_356;
  input   in_data_357;
  input   in_data_358;
  input   in_data_359;
  input   [8:0] i_index;  // ufix9
  input   par_data_0;
  input   par_data_1;
  input   par_data_2;
  input   par_data_3;
  input   par_data_4;
  input   par_data_5;
  input   par_data_6;
  input   par_data_7;
  input   par_data_8;
  input   par_data_9;
  input   par_data_10;
  input   par_data_11;
  input   par_data_12;
  input   par_data_13;
  input   par_data_14;
  input   par_data_15;
  input   par_data_16;
  input   par_data_17;
  input   par_data_18;
  input   par_data_19;
  input   par_data_20;
  input   par_data_21;
  input   par_data_22;
  input   par_data_23;
  input   par_data_24;
  input   par_data_25;
  input   par_data_26;
  input   par_data_27;
  input   par_data_28;
  input   par_data_29;
  input   par_data_30;
  input   par_data_31;
  input   par_data_32;
  input   par_data_33;
  input   par_data_34;
  input   par_data_35;
  input   par_data_36;
  input   par_data_37;
  input   par_data_38;
  input   par_data_39;
  input   par_data_40;
  input   par_data_41;
  input   par_data_42;
  input   par_data_43;
  input   par_data_44;
  input   par_data_45;
  input   par_data_46;
  input   par_data_47;
  input   par_data_48;
  input   par_data_49;
  input   par_data_50;
  input   par_data_51;
  input   par_data_52;
  input   par_data_53;
  input   par_data_54;
  input   par_data_55;
  input   par_data_56;
  input   par_data_57;
  input   par_data_58;
  input   par_data_59;
  input   par_data_60;
  input   par_data_61;
  input   par_data_62;
  input   par_data_63;
  input   par_data_64;
  input   par_data_65;
  input   par_data_66;
  input   par_data_67;
  input   par_data_68;
  input   par_data_69;
  input   par_data_70;
  input   par_data_71;
  input   par_data_72;
  input   par_data_73;
  input   par_data_74;
  input   par_data_75;
  input   par_data_76;
  input   par_data_77;
  input   par_data_78;
  input   par_data_79;
  input   par_data_80;
  input   par_data_81;
  input   par_data_82;
  input   par_data_83;
  input   par_data_84;
  input   par_data_85;
  input   par_data_86;
  input   par_data_87;
  input   par_data_88;
  input   par_data_89;
  input   par_data_90;
  input   par_data_91;
  input   par_data_92;
  input   par_data_93;
  input   par_data_94;
  input   par_data_95;
  input   par_data_96;
  input   par_data_97;
  input   par_data_98;
  input   par_data_99;
  input   par_data_100;
  input   par_data_101;
  input   par_data_102;
  input   par_data_103;
  input   par_data_104;
  input   par_data_105;
  input   par_data_106;
  input   par_data_107;
  input   par_data_108;
  input   par_data_109;
  input   par_data_110;
  input   par_data_111;
  input   par_data_112;
  input   par_data_113;
  input   par_data_114;
  input   par_data_115;
  input   par_data_116;
  input   par_data_117;
  input   par_data_118;
  input   par_data_119;
  input   par_data_120;
  input   par_data_121;
  input   par_data_122;
  input   par_data_123;
  input   par_data_124;
  input   par_data_125;
  input   par_data_126;
  input   par_data_127;
  input   par_data_128;
  input   par_data_129;
  input   par_data_130;
  input   par_data_131;
  input   par_data_132;
  input   par_data_133;
  input   par_data_134;
  input   par_data_135;
  input   par_data_136;
  input   par_data_137;
  input   par_data_138;
  input   par_data_139;
  input   par_data_140;
  input   par_data_141;
  input   par_data_142;
  input   par_data_143;
  input   par_data_144;
  input   par_data_145;
  input   par_data_146;
  input   par_data_147;
  input   par_data_148;
  input   par_data_149;
  input   par_data_150;
  input   par_data_151;
  input   par_data_152;
  input   par_data_153;
  input   par_data_154;
  input   par_data_155;
  input   par_data_156;
  input   par_data_157;
  input   par_data_158;
  input   par_data_159;
  input   par_data_160;
  input   par_data_161;
  input   par_data_162;
  input   par_data_163;
  input   par_data_164;
  input   par_data_165;
  input   par_data_166;
  input   par_data_167;
  input   par_data_168;
  input   par_data_169;
  input   par_data_170;
  input   par_data_171;
  input   par_data_172;
  input   par_data_173;
  input   par_data_174;
  input   par_data_175;
  input   par_data_176;
  input   par_data_177;
  input   par_data_178;
  input   par_data_179;
  input   par_data_180;
  input   par_data_181;
  input   par_data_182;
  input   par_data_183;
  input   par_data_184;
  input   par_data_185;
  input   par_data_186;
  input   par_data_187;
  input   par_data_188;
  input   par_data_189;
  input   par_data_190;
  input   par_data_191;
  input   par_data_192;
  input   par_data_193;
  input   par_data_194;
  input   par_data_195;
  input   par_data_196;
  input   par_data_197;
  input   par_data_198;
  input   par_data_199;
  input   par_data_200;
  input   par_data_201;
  input   par_data_202;
  input   par_data_203;
  input   par_data_204;
  input   par_data_205;
  input   par_data_206;
  input   par_data_207;
  input   par_data_208;
  input   par_data_209;
  input   par_data_210;
  input   par_data_211;
  input   par_data_212;
  input   par_data_213;
  input   par_data_214;
  input   par_data_215;
  input   par_data_216;
  input   par_data_217;
  input   par_data_218;
  input   par_data_219;
  input   par_data_220;
  input   par_data_221;
  input   par_data_222;
  input   par_data_223;
  input   par_data_224;
  input   par_data_225;
  input   par_data_226;
  input   par_data_227;
  input   par_data_228;
  input   par_data_229;
  input   par_data_230;
  input   par_data_231;
  input   par_data_232;
  input   par_data_233;
  input   par_data_234;
  input   par_data_235;
  input   par_data_236;
  input   par_data_237;
  input   par_data_238;
  input   par_data_239;
  input   par_data_240;
  input   par_data_241;
  input   par_data_242;
  input   par_data_243;
  input   par_data_244;
  input   par_data_245;
  input   par_data_246;
  input   par_data_247;
  input   par_data_248;
  input   par_data_249;
  input   par_data_250;
  input   par_data_251;
  input   par_data_252;
  input   par_data_253;
  input   par_data_254;
  input   par_data_255;
  input   par_data_256;
  input   par_data_257;
  input   par_data_258;
  input   par_data_259;
  input   par_data_260;
  input   par_data_261;
  input   par_data_262;
  input   par_data_263;
  input   par_data_264;
  input   par_data_265;
  input   par_data_266;
  input   par_data_267;
  input   par_data_268;
  input   par_data_269;
  input   par_data_270;
  input   par_data_271;
  input   par_data_272;
  input   par_data_273;
  input   par_data_274;
  input   par_data_275;
  input   par_data_276;
  input   par_data_277;
  input   par_data_278;
  input   par_data_279;
  input   par_data_280;
  input   par_data_281;
  input   par_data_282;
  input   par_data_283;
  input   par_data_284;
  input   par_data_285;
  input   par_data_286;
  input   par_data_287;
  input   par_data_288;
  input   par_data_289;
  input   par_data_290;
  input   par_data_291;
  input   par_data_292;
  input   par_data_293;
  input   par_data_294;
  input   par_data_295;
  input   par_data_296;
  input   par_data_297;
  input   par_data_298;
  input   par_data_299;
  input   par_data_300;
  input   par_data_301;
  input   par_data_302;
  input   par_data_303;
  input   par_data_304;
  input   par_data_305;
  input   par_data_306;
  input   par_data_307;
  input   par_data_308;
  input   par_data_309;
  input   par_data_310;
  input   par_data_311;
  input   par_data_312;
  input   par_data_313;
  input   par_data_314;
  input   par_data_315;
  input   par_data_316;
  input   par_data_317;
  input   par_data_318;
  input   par_data_319;
  input   par_data_320;
  input   par_data_321;
  input   par_data_322;
  input   par_data_323;
  input   par_data_324;
  input   par_data_325;
  input   par_data_326;
  input   par_data_327;
  input   par_data_328;
  input   par_data_329;
  input   par_data_330;
  input   par_data_331;
  input   par_data_332;
  input   par_data_333;
  input   par_data_334;
  input   par_data_335;
  input   par_data_336;
  input   par_data_337;
  input   par_data_338;
  input   par_data_339;
  input   par_data_340;
  input   par_data_341;
  input   par_data_342;
  input   par_data_343;
  input   par_data_344;
  input   par_data_345;
  input   par_data_346;
  input   par_data_347;
  input   par_data_348;
  input   par_data_349;
  input   par_data_350;
  input   par_data_351;
  input   par_data_352;
  input   par_data_353;
  input   par_data_354;
  input   par_data_355;
  input   par_data_356;
  input   par_data_357;
  input   par_data_358;
  input   par_data_359;
  input   [8:0] p_index;  // ufix9
  output  parity;
  output  input_rsvd;


  wire [359:0] in_data;  // boolean [360]
  wire [359:0] par_data;  // boolean [360]


  assign in_data[0] = in_data_0;
  assign in_data[1] = in_data_1;
  assign in_data[2] = in_data_2;
  assign in_data[3] = in_data_3;
  assign in_data[4] = in_data_4;
  assign in_data[5] = in_data_5;
  assign in_data[6] = in_data_6;
  assign in_data[7] = in_data_7;
  assign in_data[8] = in_data_8;
  assign in_data[9] = in_data_9;
  assign in_data[10] = in_data_10;
  assign in_data[11] = in_data_11;
  assign in_data[12] = in_data_12;
  assign in_data[13] = in_data_13;
  assign in_data[14] = in_data_14;
  assign in_data[15] = in_data_15;
  assign in_data[16] = in_data_16;
  assign in_data[17] = in_data_17;
  assign in_data[18] = in_data_18;
  assign in_data[19] = in_data_19;
  assign in_data[20] = in_data_20;
  assign in_data[21] = in_data_21;
  assign in_data[22] = in_data_22;
  assign in_data[23] = in_data_23;
  assign in_data[24] = in_data_24;
  assign in_data[25] = in_data_25;
  assign in_data[26] = in_data_26;
  assign in_data[27] = in_data_27;
  assign in_data[28] = in_data_28;
  assign in_data[29] = in_data_29;
  assign in_data[30] = in_data_30;
  assign in_data[31] = in_data_31;
  assign in_data[32] = in_data_32;
  assign in_data[33] = in_data_33;
  assign in_data[34] = in_data_34;
  assign in_data[35] = in_data_35;
  assign in_data[36] = in_data_36;
  assign in_data[37] = in_data_37;
  assign in_data[38] = in_data_38;
  assign in_data[39] = in_data_39;
  assign in_data[40] = in_data_40;
  assign in_data[41] = in_data_41;
  assign in_data[42] = in_data_42;
  assign in_data[43] = in_data_43;
  assign in_data[44] = in_data_44;
  assign in_data[45] = in_data_45;
  assign in_data[46] = in_data_46;
  assign in_data[47] = in_data_47;
  assign in_data[48] = in_data_48;
  assign in_data[49] = in_data_49;
  assign in_data[50] = in_data_50;
  assign in_data[51] = in_data_51;
  assign in_data[52] = in_data_52;
  assign in_data[53] = in_data_53;
  assign in_data[54] = in_data_54;
  assign in_data[55] = in_data_55;
  assign in_data[56] = in_data_56;
  assign in_data[57] = in_data_57;
  assign in_data[58] = in_data_58;
  assign in_data[59] = in_data_59;
  assign in_data[60] = in_data_60;
  assign in_data[61] = in_data_61;
  assign in_data[62] = in_data_62;
  assign in_data[63] = in_data_63;
  assign in_data[64] = in_data_64;
  assign in_data[65] = in_data_65;
  assign in_data[66] = in_data_66;
  assign in_data[67] = in_data_67;
  assign in_data[68] = in_data_68;
  assign in_data[69] = in_data_69;
  assign in_data[70] = in_data_70;
  assign in_data[71] = in_data_71;
  assign in_data[72] = in_data_72;
  assign in_data[73] = in_data_73;
  assign in_data[74] = in_data_74;
  assign in_data[75] = in_data_75;
  assign in_data[76] = in_data_76;
  assign in_data[77] = in_data_77;
  assign in_data[78] = in_data_78;
  assign in_data[79] = in_data_79;
  assign in_data[80] = in_data_80;
  assign in_data[81] = in_data_81;
  assign in_data[82] = in_data_82;
  assign in_data[83] = in_data_83;
  assign in_data[84] = in_data_84;
  assign in_data[85] = in_data_85;
  assign in_data[86] = in_data_86;
  assign in_data[87] = in_data_87;
  assign in_data[88] = in_data_88;
  assign in_data[89] = in_data_89;
  assign in_data[90] = in_data_90;
  assign in_data[91] = in_data_91;
  assign in_data[92] = in_data_92;
  assign in_data[93] = in_data_93;
  assign in_data[94] = in_data_94;
  assign in_data[95] = in_data_95;
  assign in_data[96] = in_data_96;
  assign in_data[97] = in_data_97;
  assign in_data[98] = in_data_98;
  assign in_data[99] = in_data_99;
  assign in_data[100] = in_data_100;
  assign in_data[101] = in_data_101;
  assign in_data[102] = in_data_102;
  assign in_data[103] = in_data_103;
  assign in_data[104] = in_data_104;
  assign in_data[105] = in_data_105;
  assign in_data[106] = in_data_106;
  assign in_data[107] = in_data_107;
  assign in_data[108] = in_data_108;
  assign in_data[109] = in_data_109;
  assign in_data[110] = in_data_110;
  assign in_data[111] = in_data_111;
  assign in_data[112] = in_data_112;
  assign in_data[113] = in_data_113;
  assign in_data[114] = in_data_114;
  assign in_data[115] = in_data_115;
  assign in_data[116] = in_data_116;
  assign in_data[117] = in_data_117;
  assign in_data[118] = in_data_118;
  assign in_data[119] = in_data_119;
  assign in_data[120] = in_data_120;
  assign in_data[121] = in_data_121;
  assign in_data[122] = in_data_122;
  assign in_data[123] = in_data_123;
  assign in_data[124] = in_data_124;
  assign in_data[125] = in_data_125;
  assign in_data[126] = in_data_126;
  assign in_data[127] = in_data_127;
  assign in_data[128] = in_data_128;
  assign in_data[129] = in_data_129;
  assign in_data[130] = in_data_130;
  assign in_data[131] = in_data_131;
  assign in_data[132] = in_data_132;
  assign in_data[133] = in_data_133;
  assign in_data[134] = in_data_134;
  assign in_data[135] = in_data_135;
  assign in_data[136] = in_data_136;
  assign in_data[137] = in_data_137;
  assign in_data[138] = in_data_138;
  assign in_data[139] = in_data_139;
  assign in_data[140] = in_data_140;
  assign in_data[141] = in_data_141;
  assign in_data[142] = in_data_142;
  assign in_data[143] = in_data_143;
  assign in_data[144] = in_data_144;
  assign in_data[145] = in_data_145;
  assign in_data[146] = in_data_146;
  assign in_data[147] = in_data_147;
  assign in_data[148] = in_data_148;
  assign in_data[149] = in_data_149;
  assign in_data[150] = in_data_150;
  assign in_data[151] = in_data_151;
  assign in_data[152] = in_data_152;
  assign in_data[153] = in_data_153;
  assign in_data[154] = in_data_154;
  assign in_data[155] = in_data_155;
  assign in_data[156] = in_data_156;
  assign in_data[157] = in_data_157;
  assign in_data[158] = in_data_158;
  assign in_data[159] = in_data_159;
  assign in_data[160] = in_data_160;
  assign in_data[161] = in_data_161;
  assign in_data[162] = in_data_162;
  assign in_data[163] = in_data_163;
  assign in_data[164] = in_data_164;
  assign in_data[165] = in_data_165;
  assign in_data[166] = in_data_166;
  assign in_data[167] = in_data_167;
  assign in_data[168] = in_data_168;
  assign in_data[169] = in_data_169;
  assign in_data[170] = in_data_170;
  assign in_data[171] = in_data_171;
  assign in_data[172] = in_data_172;
  assign in_data[173] = in_data_173;
  assign in_data[174] = in_data_174;
  assign in_data[175] = in_data_175;
  assign in_data[176] = in_data_176;
  assign in_data[177] = in_data_177;
  assign in_data[178] = in_data_178;
  assign in_data[179] = in_data_179;
  assign in_data[180] = in_data_180;
  assign in_data[181] = in_data_181;
  assign in_data[182] = in_data_182;
  assign in_data[183] = in_data_183;
  assign in_data[184] = in_data_184;
  assign in_data[185] = in_data_185;
  assign in_data[186] = in_data_186;
  assign in_data[187] = in_data_187;
  assign in_data[188] = in_data_188;
  assign in_data[189] = in_data_189;
  assign in_data[190] = in_data_190;
  assign in_data[191] = in_data_191;
  assign in_data[192] = in_data_192;
  assign in_data[193] = in_data_193;
  assign in_data[194] = in_data_194;
  assign in_data[195] = in_data_195;
  assign in_data[196] = in_data_196;
  assign in_data[197] = in_data_197;
  assign in_data[198] = in_data_198;
  assign in_data[199] = in_data_199;
  assign in_data[200] = in_data_200;
  assign in_data[201] = in_data_201;
  assign in_data[202] = in_data_202;
  assign in_data[203] = in_data_203;
  assign in_data[204] = in_data_204;
  assign in_data[205] = in_data_205;
  assign in_data[206] = in_data_206;
  assign in_data[207] = in_data_207;
  assign in_data[208] = in_data_208;
  assign in_data[209] = in_data_209;
  assign in_data[210] = in_data_210;
  assign in_data[211] = in_data_211;
  assign in_data[212] = in_data_212;
  assign in_data[213] = in_data_213;
  assign in_data[214] = in_data_214;
  assign in_data[215] = in_data_215;
  assign in_data[216] = in_data_216;
  assign in_data[217] = in_data_217;
  assign in_data[218] = in_data_218;
  assign in_data[219] = in_data_219;
  assign in_data[220] = in_data_220;
  assign in_data[221] = in_data_221;
  assign in_data[222] = in_data_222;
  assign in_data[223] = in_data_223;
  assign in_data[224] = in_data_224;
  assign in_data[225] = in_data_225;
  assign in_data[226] = in_data_226;
  assign in_data[227] = in_data_227;
  assign in_data[228] = in_data_228;
  assign in_data[229] = in_data_229;
  assign in_data[230] = in_data_230;
  assign in_data[231] = in_data_231;
  assign in_data[232] = in_data_232;
  assign in_data[233] = in_data_233;
  assign in_data[234] = in_data_234;
  assign in_data[235] = in_data_235;
  assign in_data[236] = in_data_236;
  assign in_data[237] = in_data_237;
  assign in_data[238] = in_data_238;
  assign in_data[239] = in_data_239;
  assign in_data[240] = in_data_240;
  assign in_data[241] = in_data_241;
  assign in_data[242] = in_data_242;
  assign in_data[243] = in_data_243;
  assign in_data[244] = in_data_244;
  assign in_data[245] = in_data_245;
  assign in_data[246] = in_data_246;
  assign in_data[247] = in_data_247;
  assign in_data[248] = in_data_248;
  assign in_data[249] = in_data_249;
  assign in_data[250] = in_data_250;
  assign in_data[251] = in_data_251;
  assign in_data[252] = in_data_252;
  assign in_data[253] = in_data_253;
  assign in_data[254] = in_data_254;
  assign in_data[255] = in_data_255;
  assign in_data[256] = in_data_256;
  assign in_data[257] = in_data_257;
  assign in_data[258] = in_data_258;
  assign in_data[259] = in_data_259;
  assign in_data[260] = in_data_260;
  assign in_data[261] = in_data_261;
  assign in_data[262] = in_data_262;
  assign in_data[263] = in_data_263;
  assign in_data[264] = in_data_264;
  assign in_data[265] = in_data_265;
  assign in_data[266] = in_data_266;
  assign in_data[267] = in_data_267;
  assign in_data[268] = in_data_268;
  assign in_data[269] = in_data_269;
  assign in_data[270] = in_data_270;
  assign in_data[271] = in_data_271;
  assign in_data[272] = in_data_272;
  assign in_data[273] = in_data_273;
  assign in_data[274] = in_data_274;
  assign in_data[275] = in_data_275;
  assign in_data[276] = in_data_276;
  assign in_data[277] = in_data_277;
  assign in_data[278] = in_data_278;
  assign in_data[279] = in_data_279;
  assign in_data[280] = in_data_280;
  assign in_data[281] = in_data_281;
  assign in_data[282] = in_data_282;
  assign in_data[283] = in_data_283;
  assign in_data[284] = in_data_284;
  assign in_data[285] = in_data_285;
  assign in_data[286] = in_data_286;
  assign in_data[287] = in_data_287;
  assign in_data[288] = in_data_288;
  assign in_data[289] = in_data_289;
  assign in_data[290] = in_data_290;
  assign in_data[291] = in_data_291;
  assign in_data[292] = in_data_292;
  assign in_data[293] = in_data_293;
  assign in_data[294] = in_data_294;
  assign in_data[295] = in_data_295;
  assign in_data[296] = in_data_296;
  assign in_data[297] = in_data_297;
  assign in_data[298] = in_data_298;
  assign in_data[299] = in_data_299;
  assign in_data[300] = in_data_300;
  assign in_data[301] = in_data_301;
  assign in_data[302] = in_data_302;
  assign in_data[303] = in_data_303;
  assign in_data[304] = in_data_304;
  assign in_data[305] = in_data_305;
  assign in_data[306] = in_data_306;
  assign in_data[307] = in_data_307;
  assign in_data[308] = in_data_308;
  assign in_data[309] = in_data_309;
  assign in_data[310] = in_data_310;
  assign in_data[311] = in_data_311;
  assign in_data[312] = in_data_312;
  assign in_data[313] = in_data_313;
  assign in_data[314] = in_data_314;
  assign in_data[315] = in_data_315;
  assign in_data[316] = in_data_316;
  assign in_data[317] = in_data_317;
  assign in_data[318] = in_data_318;
  assign in_data[319] = in_data_319;
  assign in_data[320] = in_data_320;
  assign in_data[321] = in_data_321;
  assign in_data[322] = in_data_322;
  assign in_data[323] = in_data_323;
  assign in_data[324] = in_data_324;
  assign in_data[325] = in_data_325;
  assign in_data[326] = in_data_326;
  assign in_data[327] = in_data_327;
  assign in_data[328] = in_data_328;
  assign in_data[329] = in_data_329;
  assign in_data[330] = in_data_330;
  assign in_data[331] = in_data_331;
  assign in_data[332] = in_data_332;
  assign in_data[333] = in_data_333;
  assign in_data[334] = in_data_334;
  assign in_data[335] = in_data_335;
  assign in_data[336] = in_data_336;
  assign in_data[337] = in_data_337;
  assign in_data[338] = in_data_338;
  assign in_data[339] = in_data_339;
  assign in_data[340] = in_data_340;
  assign in_data[341] = in_data_341;
  assign in_data[342] = in_data_342;
  assign in_data[343] = in_data_343;
  assign in_data[344] = in_data_344;
  assign in_data[345] = in_data_345;
  assign in_data[346] = in_data_346;
  assign in_data[347] = in_data_347;
  assign in_data[348] = in_data_348;
  assign in_data[349] = in_data_349;
  assign in_data[350] = in_data_350;
  assign in_data[351] = in_data_351;
  assign in_data[352] = in_data_352;
  assign in_data[353] = in_data_353;
  assign in_data[354] = in_data_354;
  assign in_data[355] = in_data_355;
  assign in_data[356] = in_data_356;
  assign in_data[357] = in_data_357;
  assign in_data[358] = in_data_358;
  assign in_data[359] = in_data_359;

  assign par_data[0] = par_data_0;
  assign par_data[1] = par_data_1;
  assign par_data[2] = par_data_2;
  assign par_data[3] = par_data_3;
  assign par_data[4] = par_data_4;
  assign par_data[5] = par_data_5;
  assign par_data[6] = par_data_6;
  assign par_data[7] = par_data_7;
  assign par_data[8] = par_data_8;
  assign par_data[9] = par_data_9;
  assign par_data[10] = par_data_10;
  assign par_data[11] = par_data_11;
  assign par_data[12] = par_data_12;
  assign par_data[13] = par_data_13;
  assign par_data[14] = par_data_14;
  assign par_data[15] = par_data_15;
  assign par_data[16] = par_data_16;
  assign par_data[17] = par_data_17;
  assign par_data[18] = par_data_18;
  assign par_data[19] = par_data_19;
  assign par_data[20] = par_data_20;
  assign par_data[21] = par_data_21;
  assign par_data[22] = par_data_22;
  assign par_data[23] = par_data_23;
  assign par_data[24] = par_data_24;
  assign par_data[25] = par_data_25;
  assign par_data[26] = par_data_26;
  assign par_data[27] = par_data_27;
  assign par_data[28] = par_data_28;
  assign par_data[29] = par_data_29;
  assign par_data[30] = par_data_30;
  assign par_data[31] = par_data_31;
  assign par_data[32] = par_data_32;
  assign par_data[33] = par_data_33;
  assign par_data[34] = par_data_34;
  assign par_data[35] = par_data_35;
  assign par_data[36] = par_data_36;
  assign par_data[37] = par_data_37;
  assign par_data[38] = par_data_38;
  assign par_data[39] = par_data_39;
  assign par_data[40] = par_data_40;
  assign par_data[41] = par_data_41;
  assign par_data[42] = par_data_42;
  assign par_data[43] = par_data_43;
  assign par_data[44] = par_data_44;
  assign par_data[45] = par_data_45;
  assign par_data[46] = par_data_46;
  assign par_data[47] = par_data_47;
  assign par_data[48] = par_data_48;
  assign par_data[49] = par_data_49;
  assign par_data[50] = par_data_50;
  assign par_data[51] = par_data_51;
  assign par_data[52] = par_data_52;
  assign par_data[53] = par_data_53;
  assign par_data[54] = par_data_54;
  assign par_data[55] = par_data_55;
  assign par_data[56] = par_data_56;
  assign par_data[57] = par_data_57;
  assign par_data[58] = par_data_58;
  assign par_data[59] = par_data_59;
  assign par_data[60] = par_data_60;
  assign par_data[61] = par_data_61;
  assign par_data[62] = par_data_62;
  assign par_data[63] = par_data_63;
  assign par_data[64] = par_data_64;
  assign par_data[65] = par_data_65;
  assign par_data[66] = par_data_66;
  assign par_data[67] = par_data_67;
  assign par_data[68] = par_data_68;
  assign par_data[69] = par_data_69;
  assign par_data[70] = par_data_70;
  assign par_data[71] = par_data_71;
  assign par_data[72] = par_data_72;
  assign par_data[73] = par_data_73;
  assign par_data[74] = par_data_74;
  assign par_data[75] = par_data_75;
  assign par_data[76] = par_data_76;
  assign par_data[77] = par_data_77;
  assign par_data[78] = par_data_78;
  assign par_data[79] = par_data_79;
  assign par_data[80] = par_data_80;
  assign par_data[81] = par_data_81;
  assign par_data[82] = par_data_82;
  assign par_data[83] = par_data_83;
  assign par_data[84] = par_data_84;
  assign par_data[85] = par_data_85;
  assign par_data[86] = par_data_86;
  assign par_data[87] = par_data_87;
  assign par_data[88] = par_data_88;
  assign par_data[89] = par_data_89;
  assign par_data[90] = par_data_90;
  assign par_data[91] = par_data_91;
  assign par_data[92] = par_data_92;
  assign par_data[93] = par_data_93;
  assign par_data[94] = par_data_94;
  assign par_data[95] = par_data_95;
  assign par_data[96] = par_data_96;
  assign par_data[97] = par_data_97;
  assign par_data[98] = par_data_98;
  assign par_data[99] = par_data_99;
  assign par_data[100] = par_data_100;
  assign par_data[101] = par_data_101;
  assign par_data[102] = par_data_102;
  assign par_data[103] = par_data_103;
  assign par_data[104] = par_data_104;
  assign par_data[105] = par_data_105;
  assign par_data[106] = par_data_106;
  assign par_data[107] = par_data_107;
  assign par_data[108] = par_data_108;
  assign par_data[109] = par_data_109;
  assign par_data[110] = par_data_110;
  assign par_data[111] = par_data_111;
  assign par_data[112] = par_data_112;
  assign par_data[113] = par_data_113;
  assign par_data[114] = par_data_114;
  assign par_data[115] = par_data_115;
  assign par_data[116] = par_data_116;
  assign par_data[117] = par_data_117;
  assign par_data[118] = par_data_118;
  assign par_data[119] = par_data_119;
  assign par_data[120] = par_data_120;
  assign par_data[121] = par_data_121;
  assign par_data[122] = par_data_122;
  assign par_data[123] = par_data_123;
  assign par_data[124] = par_data_124;
  assign par_data[125] = par_data_125;
  assign par_data[126] = par_data_126;
  assign par_data[127] = par_data_127;
  assign par_data[128] = par_data_128;
  assign par_data[129] = par_data_129;
  assign par_data[130] = par_data_130;
  assign par_data[131] = par_data_131;
  assign par_data[132] = par_data_132;
  assign par_data[133] = par_data_133;
  assign par_data[134] = par_data_134;
  assign par_data[135] = par_data_135;
  assign par_data[136] = par_data_136;
  assign par_data[137] = par_data_137;
  assign par_data[138] = par_data_138;
  assign par_data[139] = par_data_139;
  assign par_data[140] = par_data_140;
  assign par_data[141] = par_data_141;
  assign par_data[142] = par_data_142;
  assign par_data[143] = par_data_143;
  assign par_data[144] = par_data_144;
  assign par_data[145] = par_data_145;
  assign par_data[146] = par_data_146;
  assign par_data[147] = par_data_147;
  assign par_data[148] = par_data_148;
  assign par_data[149] = par_data_149;
  assign par_data[150] = par_data_150;
  assign par_data[151] = par_data_151;
  assign par_data[152] = par_data_152;
  assign par_data[153] = par_data_153;
  assign par_data[154] = par_data_154;
  assign par_data[155] = par_data_155;
  assign par_data[156] = par_data_156;
  assign par_data[157] = par_data_157;
  assign par_data[158] = par_data_158;
  assign par_data[159] = par_data_159;
  assign par_data[160] = par_data_160;
  assign par_data[161] = par_data_161;
  assign par_data[162] = par_data_162;
  assign par_data[163] = par_data_163;
  assign par_data[164] = par_data_164;
  assign par_data[165] = par_data_165;
  assign par_data[166] = par_data_166;
  assign par_data[167] = par_data_167;
  assign par_data[168] = par_data_168;
  assign par_data[169] = par_data_169;
  assign par_data[170] = par_data_170;
  assign par_data[171] = par_data_171;
  assign par_data[172] = par_data_172;
  assign par_data[173] = par_data_173;
  assign par_data[174] = par_data_174;
  assign par_data[175] = par_data_175;
  assign par_data[176] = par_data_176;
  assign par_data[177] = par_data_177;
  assign par_data[178] = par_data_178;
  assign par_data[179] = par_data_179;
  assign par_data[180] = par_data_180;
  assign par_data[181] = par_data_181;
  assign par_data[182] = par_data_182;
  assign par_data[183] = par_data_183;
  assign par_data[184] = par_data_184;
  assign par_data[185] = par_data_185;
  assign par_data[186] = par_data_186;
  assign par_data[187] = par_data_187;
  assign par_data[188] = par_data_188;
  assign par_data[189] = par_data_189;
  assign par_data[190] = par_data_190;
  assign par_data[191] = par_data_191;
  assign par_data[192] = par_data_192;
  assign par_data[193] = par_data_193;
  assign par_data[194] = par_data_194;
  assign par_data[195] = par_data_195;
  assign par_data[196] = par_data_196;
  assign par_data[197] = par_data_197;
  assign par_data[198] = par_data_198;
  assign par_data[199] = par_data_199;
  assign par_data[200] = par_data_200;
  assign par_data[201] = par_data_201;
  assign par_data[202] = par_data_202;
  assign par_data[203] = par_data_203;
  assign par_data[204] = par_data_204;
  assign par_data[205] = par_data_205;
  assign par_data[206] = par_data_206;
  assign par_data[207] = par_data_207;
  assign par_data[208] = par_data_208;
  assign par_data[209] = par_data_209;
  assign par_data[210] = par_data_210;
  assign par_data[211] = par_data_211;
  assign par_data[212] = par_data_212;
  assign par_data[213] = par_data_213;
  assign par_data[214] = par_data_214;
  assign par_data[215] = par_data_215;
  assign par_data[216] = par_data_216;
  assign par_data[217] = par_data_217;
  assign par_data[218] = par_data_218;
  assign par_data[219] = par_data_219;
  assign par_data[220] = par_data_220;
  assign par_data[221] = par_data_221;
  assign par_data[222] = par_data_222;
  assign par_data[223] = par_data_223;
  assign par_data[224] = par_data_224;
  assign par_data[225] = par_data_225;
  assign par_data[226] = par_data_226;
  assign par_data[227] = par_data_227;
  assign par_data[228] = par_data_228;
  assign par_data[229] = par_data_229;
  assign par_data[230] = par_data_230;
  assign par_data[231] = par_data_231;
  assign par_data[232] = par_data_232;
  assign par_data[233] = par_data_233;
  assign par_data[234] = par_data_234;
  assign par_data[235] = par_data_235;
  assign par_data[236] = par_data_236;
  assign par_data[237] = par_data_237;
  assign par_data[238] = par_data_238;
  assign par_data[239] = par_data_239;
  assign par_data[240] = par_data_240;
  assign par_data[241] = par_data_241;
  assign par_data[242] = par_data_242;
  assign par_data[243] = par_data_243;
  assign par_data[244] = par_data_244;
  assign par_data[245] = par_data_245;
  assign par_data[246] = par_data_246;
  assign par_data[247] = par_data_247;
  assign par_data[248] = par_data_248;
  assign par_data[249] = par_data_249;
  assign par_data[250] = par_data_250;
  assign par_data[251] = par_data_251;
  assign par_data[252] = par_data_252;
  assign par_data[253] = par_data_253;
  assign par_data[254] = par_data_254;
  assign par_data[255] = par_data_255;
  assign par_data[256] = par_data_256;
  assign par_data[257] = par_data_257;
  assign par_data[258] = par_data_258;
  assign par_data[259] = par_data_259;
  assign par_data[260] = par_data_260;
  assign par_data[261] = par_data_261;
  assign par_data[262] = par_data_262;
  assign par_data[263] = par_data_263;
  assign par_data[264] = par_data_264;
  assign par_data[265] = par_data_265;
  assign par_data[266] = par_data_266;
  assign par_data[267] = par_data_267;
  assign par_data[268] = par_data_268;
  assign par_data[269] = par_data_269;
  assign par_data[270] = par_data_270;
  assign par_data[271] = par_data_271;
  assign par_data[272] = par_data_272;
  assign par_data[273] = par_data_273;
  assign par_data[274] = par_data_274;
  assign par_data[275] = par_data_275;
  assign par_data[276] = par_data_276;
  assign par_data[277] = par_data_277;
  assign par_data[278] = par_data_278;
  assign par_data[279] = par_data_279;
  assign par_data[280] = par_data_280;
  assign par_data[281] = par_data_281;
  assign par_data[282] = par_data_282;
  assign par_data[283] = par_data_283;
  assign par_data[284] = par_data_284;
  assign par_data[285] = par_data_285;
  assign par_data[286] = par_data_286;
  assign par_data[287] = par_data_287;
  assign par_data[288] = par_data_288;
  assign par_data[289] = par_data_289;
  assign par_data[290] = par_data_290;
  assign par_data[291] = par_data_291;
  assign par_data[292] = par_data_292;
  assign par_data[293] = par_data_293;
  assign par_data[294] = par_data_294;
  assign par_data[295] = par_data_295;
  assign par_data[296] = par_data_296;
  assign par_data[297] = par_data_297;
  assign par_data[298] = par_data_298;
  assign par_data[299] = par_data_299;
  assign par_data[300] = par_data_300;
  assign par_data[301] = par_data_301;
  assign par_data[302] = par_data_302;
  assign par_data[303] = par_data_303;
  assign par_data[304] = par_data_304;
  assign par_data[305] = par_data_305;
  assign par_data[306] = par_data_306;
  assign par_data[307] = par_data_307;
  assign par_data[308] = par_data_308;
  assign par_data[309] = par_data_309;
  assign par_data[310] = par_data_310;
  assign par_data[311] = par_data_311;
  assign par_data[312] = par_data_312;
  assign par_data[313] = par_data_313;
  assign par_data[314] = par_data_314;
  assign par_data[315] = par_data_315;
  assign par_data[316] = par_data_316;
  assign par_data[317] = par_data_317;
  assign par_data[318] = par_data_318;
  assign par_data[319] = par_data_319;
  assign par_data[320] = par_data_320;
  assign par_data[321] = par_data_321;
  assign par_data[322] = par_data_322;
  assign par_data[323] = par_data_323;
  assign par_data[324] = par_data_324;
  assign par_data[325] = par_data_325;
  assign par_data[326] = par_data_326;
  assign par_data[327] = par_data_327;
  assign par_data[328] = par_data_328;
  assign par_data[329] = par_data_329;
  assign par_data[330] = par_data_330;
  assign par_data[331] = par_data_331;
  assign par_data[332] = par_data_332;
  assign par_data[333] = par_data_333;
  assign par_data[334] = par_data_334;
  assign par_data[335] = par_data_335;
  assign par_data[336] = par_data_336;
  assign par_data[337] = par_data_337;
  assign par_data[338] = par_data_338;
  assign par_data[339] = par_data_339;
  assign par_data[340] = par_data_340;
  assign par_data[341] = par_data_341;
  assign par_data[342] = par_data_342;
  assign par_data[343] = par_data_343;
  assign par_data[344] = par_data_344;
  assign par_data[345] = par_data_345;
  assign par_data[346] = par_data_346;
  assign par_data[347] = par_data_347;
  assign par_data[348] = par_data_348;
  assign par_data[349] = par_data_349;
  assign par_data[350] = par_data_350;
  assign par_data[351] = par_data_351;
  assign par_data[352] = par_data_352;
  assign par_data[353] = par_data_353;
  assign par_data[354] = par_data_354;
  assign par_data[355] = par_data_355;
  assign par_data[356] = par_data_356;
  assign par_data[357] = par_data_357;
  assign par_data[358] = par_data_358;
  assign par_data[359] = par_data_359;

//   assign parity = par_data[$signed({1'b0, p_index}) - 32'sd1];
assign parity = par_data[({1'b0, p_index}) - 32'sd1];
//   assign input_rsvd = in_data[$signed({1'b0, i_index}) - 32'sd1];
assign input_rsvd = in_data[({1'b0, i_index}) - 32'sd1];



endmodule  // dvbs2hdlTransmitterCore_Indexing

