// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_Dummy_Frame_Generator.v
// Created: 2024-01-10 13:49:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_Dummy_Frame_Generator
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/PL Frame Generator/RAM FIFO/PL Data FIFO/Dummy Frame Generator
// Hierarchy Level: 6
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_Dummy_Frame_Generator
          (clk,
           reset,
           enb_1_8_0,
           frameLength,
           EOF,
           readyNxtFrame,
           data_re,
           data_im,
           valid1,
           valid,
           headerStart,
           headerEnd);


  input   clk;
  input   reset;
  input   enb_1_8_0;
  input   [14:0] frameLength;  // ufix15
  input   EOF;
  input   readyNxtFrame;
  output  signed [17:0] data_re;  // sfix18_En16
  output  signed [17:0] data_im;  // sfix18_En16
  output  valid1;
  output  valid;
  output  headerStart;
  output  headerEnd;


  wire [11:0] countOut;  // ufix12
  wire validm2;
  wire Compare_To_Constant2_out1;
  wire signed [17:0] Constant_out1_re;  // sfix18_En16
  wire signed [17:0] Constant_out1_im;  // sfix18_En16
  reg signed [17:0] delayMatch_reg_re [0:1];  // sfix18_En16 [2]
  reg signed [17:0] delayMatch_reg_im [0:1];  // sfix18_En16 [2]
  wire signed [17:0] delayMatch_reg_next_re [0:1];  // sfix18_En16 [2]
  wire signed [17:0] delayMatch_reg_next_im [0:1];  // sfix18_En16 [2]
  wire signed [17:0] Constant_out1_re_1;  // sfix18_En16
  wire signed [17:0] Constant_out1_im_1;  // sfix18_En16
  wire Compare_To_Constant_out1;
  wire Compare_To_Constant1_out1;
  wire Logical_Operator_out1;
  wire [6:0] Data_Type_Conversion_out1;  // ufix7
  wire [6:0] prelookup_idx_sat;  // ufix7
  wire [6:0] prelookup_idx;  // ufix7
  wire signed [17:0] Dummy_Frame_Normal_Header_table_data [0:89];  // sfix18_En16 [90]
  wire signed [17:0] realOut;  // sfix18_En16
  wire signed [17:0] Dummy_Frame_Normal_Header_table_data_1 [0:89];  // sfix18_En16 [90]
  wire signed [17:0] imagOut;  // sfix18_En16
  wire [6:0] prelookup_idx_sat_1;  // ufix7
  wire [6:0] prelookup_idx_1;  // ufix7
  wire signed [17:0] Dummy_Frame_Short_Header_table_data [0:89];  // sfix18_En16 [90]
  wire signed [17:0] realOut_1;  // sfix18_En16
  wire signed [17:0] Dummy_Frame_Short_Header_table_data_1 [0:89];  // sfix18_En16 [90]
  wire signed [17:0] imagOut_1;  // sfix18_En16
  wire signed [17:0] Switch_out1_re;  // sfix18_En16
  wire signed [17:0] Switch_out1_im;  // sfix18_En16
  wire signed [17:0] Switch1_out1_re;  // sfix18_En16
  wire signed [17:0] Switch1_out1_im;  // sfix18_En16
  wire Compare_To_Constant3_out1;
  wire Logical_Operator1_out1;
  wire Compare_To_Constant4_out1;
  wire Logical_Operator2_out1;
  reg signed [31:0] delayMatch_t_0_0;  // int32
  reg signed [31:0] delayMatch_t_1;  // int32


  dvbs2hdlTransmitterCore_Dummy_Frame_Header_LUT_Address_Generator u_Dummy_Frame_Header_LUT_Address_Generator (.clk(clk),
                                                                                                               .reset(reset),
                                                                                                               .enb_1_8_0(enb_1_8_0),
                                                                                                               .nextFrameReady(readyNxtFrame),
                                                                                                               .EOF(EOF),
                                                                                                               .countOut(countOut),  // ufix12
                                                                                                               .validm2(validm2),
                                                                                                               .valid(valid)
                                                                                                               );

  assign Compare_To_Constant2_out1 = countOut < 12'b000001011010;



  assign Constant_out1_re = 18'sb001011010100000101;
  assign Constant_out1_im = 18'sb001011010100000101;



  always @(posedge clk or posedge reset)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        for(delayMatch_t_1 = 32'sd0; delayMatch_t_1 <= 32'sd1; delayMatch_t_1 = delayMatch_t_1 + 32'sd1) begin
          delayMatch_reg_re[delayMatch_t_1] <= 18'sb000000000000000000;
          delayMatch_reg_im[delayMatch_t_1] <= 18'sb000000000000000000;
        end
      end
      else begin
        if (enb_1_8_0) begin
          for(delayMatch_t_0_0 = 32'sd0; delayMatch_t_0_0 <= 32'sd1; delayMatch_t_0_0 = delayMatch_t_0_0 + 32'sd1) begin
            delayMatch_reg_re[delayMatch_t_0_0] <= delayMatch_reg_next_re[delayMatch_t_0_0];
            delayMatch_reg_im[delayMatch_t_0_0] <= delayMatch_reg_next_im[delayMatch_t_0_0];
          end
        end
      end
    end

  assign Constant_out1_re_1 = delayMatch_reg_re[1];
  assign Constant_out1_im_1 = delayMatch_reg_im[1];
  assign delayMatch_reg_next_re[0] = Constant_out1_re;
  assign delayMatch_reg_next_im[0] = Constant_out1_im;
  assign delayMatch_reg_next_re[1] = delayMatch_reg_re[0];
  assign delayMatch_reg_next_im[1] = delayMatch_reg_im[0];



  assign Compare_To_Constant_out1 = frameLength != 15'b000000000000000;



  assign Compare_To_Constant1_out1 = frameLength <= 15'b010100100100010;



  assign Logical_Operator_out1 = Compare_To_Constant_out1 & Compare_To_Constant1_out1;



  assign Data_Type_Conversion_out1 = countOut[6:0];



  assign prelookup_idx_sat = (Data_Type_Conversion_out1 == 7'b0000000 ? 7'b0000000 :
              (Data_Type_Conversion_out1 >= 7'b1011001 ? 7'b1011001 :
              Data_Type_Conversion_out1));



  assign prelookup_idx = (prelookup_idx_sat > 7'b1011001 ? 7'b1011001 :
              prelookup_idx_sat);



  assign Dummy_Frame_Normal_Header_table_data[0] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[1] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[2] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[3] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[4] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[5] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[6] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[7] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[8] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[9] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[10] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[11] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[12] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[13] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[14] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[15] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[16] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[17] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[18] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[19] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[20] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[21] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[22] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[23] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[24] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[25] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[26] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[27] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[28] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[29] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[30] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[31] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[32] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[33] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[34] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[35] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[36] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[37] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[38] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[39] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[40] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[41] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[42] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[43] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[44] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[45] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[46] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[47] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[48] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[49] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[50] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[51] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[52] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[53] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[54] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[55] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[56] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[57] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[58] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[59] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[60] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[61] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[62] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[63] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[64] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[65] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[66] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[67] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[68] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[69] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[70] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[71] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[72] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[73] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[74] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[75] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[76] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[77] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[78] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[79] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[80] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[81] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[82] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[83] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[84] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[85] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[86] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[87] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data[88] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data[89] = 18'sb001011010100000101;
  assign realOut = Dummy_Frame_Normal_Header_table_data[prelookup_idx];



  assign Dummy_Frame_Normal_Header_table_data_1[0] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[1] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[2] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[3] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[4] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[5] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[6] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[7] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[8] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[9] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[10] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[11] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[12] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[13] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[14] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[15] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[16] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[17] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[18] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[19] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[20] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[21] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[22] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[23] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[24] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[25] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[26] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[27] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[28] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[29] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[30] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[31] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[32] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[33] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[34] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[35] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[36] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[37] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[38] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[39] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[40] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[41] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[42] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[43] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[44] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[45] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[46] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[47] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[48] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[49] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[50] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[51] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[52] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[53] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[54] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[55] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[56] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[57] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[58] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[59] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[60] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[61] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[62] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[63] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[64] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[65] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[66] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[67] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[68] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[69] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[70] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[71] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[72] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[73] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[74] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[75] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[76] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[77] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[78] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[79] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[80] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[81] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[82] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[83] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[84] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[85] = 18'sb001011010100000101;
  assign Dummy_Frame_Normal_Header_table_data_1[86] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[87] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[88] = 18'sb110100101011111011;
  assign Dummy_Frame_Normal_Header_table_data_1[89] = 18'sb110100101011111011;
  assign imagOut = Dummy_Frame_Normal_Header_table_data_1[prelookup_idx];



  assign prelookup_idx_sat_1 = (Data_Type_Conversion_out1 == 7'b0000000 ? 7'b0000000 :
              (Data_Type_Conversion_out1 >= 7'b1011001 ? 7'b1011001 :
              Data_Type_Conversion_out1));



  assign prelookup_idx_1 = (prelookup_idx_sat_1 > 7'b1011001 ? 7'b1011001 :
              prelookup_idx_sat_1);



  assign Dummy_Frame_Short_Header_table_data[0] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[1] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[2] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[3] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[4] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[5] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[6] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[7] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[8] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[9] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[10] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[11] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[12] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[13] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[14] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[15] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[16] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[17] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[18] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[19] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[20] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[21] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[22] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[23] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[24] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[25] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[26] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[27] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[28] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[29] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[30] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[31] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[32] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[33] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[34] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[35] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[36] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[37] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[38] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[39] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[40] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[41] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[42] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[43] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[44] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[45] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[46] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[47] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[48] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[49] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[50] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[51] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[52] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[53] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[54] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[55] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[56] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[57] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[58] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[59] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[60] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[61] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[62] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[63] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[64] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[65] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[66] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[67] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[68] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[69] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[70] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[71] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[72] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[73] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[74] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[75] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[76] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[77] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[78] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[79] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[80] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[81] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[82] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[83] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[84] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[85] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[86] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[87] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data[88] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data[89] = 18'sb110100101011111011;
  assign realOut_1 = Dummy_Frame_Short_Header_table_data[prelookup_idx_1];



  assign Dummy_Frame_Short_Header_table_data_1[0] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[1] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[2] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[3] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[4] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[5] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[6] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[7] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[8] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[9] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[10] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[11] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[12] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[13] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[14] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[15] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[16] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[17] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[18] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[19] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[20] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[21] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[22] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[23] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[24] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[25] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[26] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[27] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[28] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[29] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[30] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[31] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[32] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[33] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[34] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[35] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[36] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[37] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[38] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[39] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[40] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[41] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[42] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[43] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[44] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[45] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[46] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[47] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[48] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[49] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[50] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[51] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[52] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[53] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[54] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[55] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[56] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[57] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[58] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[59] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[60] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[61] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[62] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[63] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[64] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[65] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[66] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[67] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[68] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[69] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[70] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[71] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[72] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[73] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[74] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[75] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[76] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[77] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[78] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[79] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[80] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[81] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[82] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[83] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[84] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[85] = 18'sb110100101011111011;
  assign Dummy_Frame_Short_Header_table_data_1[86] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[87] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[88] = 18'sb001011010100000101;
  assign Dummy_Frame_Short_Header_table_data_1[89] = 18'sb001011010100000101;
  assign imagOut_1 = Dummy_Frame_Short_Header_table_data_1[prelookup_idx_1];



  assign Switch_out1_re = (Logical_Operator_out1 == 1'b0 ? realOut :
              realOut_1);
  assign Switch_out1_im = (Logical_Operator_out1 == 1'b0 ? imagOut :
              imagOut_1);



  assign Switch1_out1_re = (Compare_To_Constant2_out1 == 1'b0 ? Constant_out1_re_1 :
              Switch_out1_re);
  assign Switch1_out1_im = (Compare_To_Constant2_out1 == 1'b0 ? Constant_out1_im_1 :
              Switch_out1_im);



  assign data_re = Switch1_out1_re;

  assign data_im = Switch1_out1_im;

  assign valid1 = validm2;

  assign Compare_To_Constant3_out1 = countOut == 12'b000000000000;



  assign Logical_Operator1_out1 = valid & Compare_To_Constant3_out1;



  assign headerStart = Logical_Operator1_out1;

  assign Compare_To_Constant4_out1 = countOut == 12'b000001011001;



  assign Logical_Operator2_out1 = valid & Compare_To_Constant4_out1;



  assign headerEnd = Logical_Operator2_out1;

endmodule  // dvbs2hdlTransmitterCore_Dummy_Frame_Generator

