// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_Wrap_Address.v
// Created: 2024-01-10 13:49:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_Wrap_Address
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/Interleaver/DVB-S2 HDL Interleaver/RAM/Wrap Address
// Hierarchy Level: 6
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_Wrap_Address
          (u,
           y);


  input   [17:0] u;  // ufix18
  output  [16:0] y;  // ufix17


  wire Compare_To_Constant_out1;
  wire [17:0] Constant1_out1;  // ufix18
  wire [17:0] Constant_out1;  // ufix18
  wire [17:0] Switch1_out1;  // ufix18
  wire signed [18:0] Add_sub_temp;  // sfix19
  wire signed [18:0] Add_1;  // sfix19
  wire signed [18:0] Add_2;  // sfix19
  wire [17:0] Add_out1;  // ufix18
  wire [17:0] Switch_out1;  // ufix18
  wire [16:0] Data_Type_Conversion_out1;  // ufix17


  assign Compare_To_Constant_out1 = u >= 18'b011111101001000000;



  assign Constant1_out1 = 18'b000000000000000000;



  assign Constant_out1 = 18'b011111101001000000;



  assign Switch1_out1 = (Compare_To_Constant_out1 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign Add_1 = {1'b0, u};
  assign Add_2 = {1'b0, Switch1_out1};
  assign Add_sub_temp = Add_1 - Add_2;
  assign Add_out1 = Add_sub_temp[17:0];



  assign Switch_out1 = (Compare_To_Constant_out1 == 1'b0 ? u :
              Add_out1);



  assign Data_Type_Conversion_out1 = Switch_out1[16:0];



  assign y = Data_Type_Conversion_out1;

endmodule  // dvbs2hdlTransmitterCore_Wrap_Address

