// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_Pilot_Generator.v
// Created: 2024-01-10 13:49:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_Pilot_Generator
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/PL Frame Generator/RAM FIFO/Pilot Generator
// Hierarchy Level: 5
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_Pilot_Generator
          (clk,
           reset,
           enb_1_8_0,
           trigger,
           dataOut_re,
           dataOut_im,
           validOut,
           endOut1);


  input   clk;
  input   reset;
  input   enb_1_8_0;
  input   trigger;
  output  signed [17:0] dataOut_re;  // sfix18_En16
  output  signed [17:0] dataOut_im;  // sfix18_En16
  output  validOut;
  output  endOut1;


  wire signed [17:0] Pilot_or_Unmodulated_Carrier_out1_re;  // sfix18_En16
  wire signed [17:0] Pilot_or_Unmodulated_Carrier_out1_im;  // sfix18_En16
  wire endOutm1;


  assign Pilot_or_Unmodulated_Carrier_out1_re = 18'sb001011010100000101;
  assign Pilot_or_Unmodulated_Carrier_out1_im = 18'sb001011010100000101;



  assign dataOut_re = Pilot_or_Unmodulated_Carrier_out1_re;

  assign dataOut_im = Pilot_or_Unmodulated_Carrier_out1_im;

  dvbs2hdlTransmitterCore_Pilot_Block_Length_Valid_Generator u_Pilot_Block_Length_Valid_Generator (.clk(clk),
                                                                                                   .reset(reset),
                                                                                                   .enb_1_8_0(enb_1_8_0),
                                                                                                   .trigger(trigger),
                                                                                                   .endOutm1(endOutm1),
                                                                                                   .validOut(validOut)
                                                                                                   );

  assign endOut1 = endOutm1;

endmodule  // dvbs2hdlTransmitterCore_Pilot_Generator

