// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_Subsystem.v
// Created: 2024-01-10 13:49:57
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_Subsystem
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/BB Frame Generator/BB Scrambler/Subsystem
// Hierarchy Level: 5
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_Subsystem
          (clk,
           reset,
           enb,
           In1,
           Enable,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   In1;
  input   Enable;
  output  Out1;  // ufix1


  wire enb_gated;
  wire PN_Sequence_Generator_out1;  // ufix1
  wire PN_Sequence_Generator_out1_bypass;  // ufix1
  reg  PN_Sequence_Generator_out1_last_value;  // ufix1


  assign enb_gated = Enable && enb;

  dvbs2hdlTransmitterCore_PN_Sequence_Generator u_PN_Sequence_Generator (.clk(clk),
                                                                         .reset(reset),
                                                                         .enb(enb_gated),
                                                                         .inportReset(In1),
                                                                         .PN_Sequence(PN_Sequence_Generator_out1)  // ufix1
                                                                         );

  always @(posedge clk or posedge reset)
    begin : Out1_bypass_process
      if (reset == 1'b1) begin
        PN_Sequence_Generator_out1_last_value <= 1'b0;
      end
      else begin
        if (enb_gated) begin
          PN_Sequence_Generator_out1_last_value <= PN_Sequence_Generator_out1_bypass;
        end
      end
    end



  assign PN_Sequence_Generator_out1_bypass = (Enable == 1'b0 ? PN_Sequence_Generator_out1_last_value :
              PN_Sequence_Generator_out1);



  assign Out1 = PN_Sequence_Generator_out1_bypass;

endmodule  // dvbs2hdlTransmitterCore_Subsystem

