// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_Sample_Control_Bus_Creator_block.v
// Created: 2024-01-10 13:49:57
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_Sample_Control_Bus_Creator_block
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/FEC Encoder/DVB-S2 LDPC Encoder/Sample Control Bus Creator
// Hierarchy Level: 5
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_Sample_Control_Bus_Creator_block
          (In1,
           In3,
           Out1_start,
           Out1_valid);


  input   In1;
  input   In3;
  output  Out1_start;
  output  Out1_valid;


  wire In2;
  wire Out1_end;


  assign Out1_start = In1;

  assign Out1_valid = In3;

endmodule  // dvbs2hdlTransmitterCore_Sample_Control_Bus_Creator_block

