// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_FIFO_3_Variables.v
// Created: 2024-01-10 13:49:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_FIFO_3_Variables
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/Interleaver/DVB-S2 HDL Interleaver/RAM Address Generator/Read Offset 
// Address/Read Offset Address Signals Generator/FIFO 3 Variable
// Hierarchy Level: 8
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_FIFO_3_Variables
          (clk,
           reset,
           enb,
           maxR,
           push,
           pop,
           maxC,
           modcodis12,
           vMaxR,
           vMaxC,
           vMODCODis12);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] maxR;  // uint16
  input   push;
  input   pop;
  input   [2:0] maxC;  // ufix3
  input   modcodis12;
  output  [15:0] vMaxR;  // uint16
  output  [2:0] vMaxC;  // ufix3
  output  vMODCODis12;


  wire [2:0] count_step;  // ufix3
  wire [2:0] count_from;  // ufix3
  reg [2:0] HDL_Counter_out1;  // ufix3
  wire [2:0] count;  // ufix3
  wire need_to_wrap;
  wire [2:0] count_value;  // ufix3
  wire [2:0] count_1;  // ufix3
  wire [2:0] count_step_1;  // ufix3
  wire [2:0] count_from_1;  // ufix3
  reg [2:0] HDL_Counter1_out1;  // ufix3
  wire [2:0] count_2;  // ufix3
  wire need_to_wrap_1;
  wire [2:0] count_value_1;  // ufix3
  wire [2:0] count_3;  // ufix3
  wire [15:0] Simple_Dual_Port_RAM1_out1;  // uint16
  wire [2:0] Simple_Dual_Port_RAM_out1;  // ufix3
  wire Simple_Dual_Port_RAM2_out1;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 7
  assign count_step = 3'b001;



  assign count_from = 3'b000;



  assign count = HDL_Counter_out1 + count_step;



  assign need_to_wrap = HDL_Counter_out1 == 3'b111;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  assign count_1 = (push == 1'b0 ? HDL_Counter_out1 :
              count_value);



  always @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 3'b000;
      end
      else begin
        if (enb) begin
          HDL_Counter_out1 <= count_1;
        end
      end
    end



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 7
  assign count_step_1 = 3'b001;



  assign count_from_1 = 3'b000;



  assign count_2 = HDL_Counter1_out1 + count_step_1;



  assign need_to_wrap_1 = HDL_Counter1_out1 == 3'b111;



  assign count_value_1 = (need_to_wrap_1 == 1'b0 ? count_2 :
              count_from_1);



  assign count_3 = (pop == 1'b0 ? HDL_Counter1_out1 :
              count_value_1);



  always @(posedge clk or posedge reset)
    begin : HDL_Counter1_process
      if (reset == 1'b1) begin
        HDL_Counter1_out1 <= 3'b000;
      end
      else begin
        if (enb) begin
          HDL_Counter1_out1 <= count_3;
        end
      end
    end



  dvbs2hdlTransmitterCore_SimpleDualPortRAM_generic_block #(.AddrWidth(3),
                                                            .DataWidth(16)
                                                            )
                                                          u_Simple_Dual_Port_RAM1 (.clk(clk),
                                                                                   .enb(enb),
                                                                                   .wr_din(maxR),
                                                                                   .wr_addr(HDL_Counter_out1),
                                                                                   .wr_en(push),
                                                                                   .rd_addr(HDL_Counter1_out1),
                                                                                   .dout(Simple_Dual_Port_RAM1_out1)
                                                                                   );

  assign vMaxR = Simple_Dual_Port_RAM1_out1;

  dvbs2hdlTransmitterCore_SimpleDualPortRAM_generic_block #(.AddrWidth(3),
                                                            .DataWidth(3)
                                                            )
                                                          u_Simple_Dual_Port_RAM (.clk(clk),
                                                                                  .enb(enb),
                                                                                  .wr_din(maxC),
                                                                                  .wr_addr(HDL_Counter_out1),
                                                                                  .wr_en(push),
                                                                                  .rd_addr(HDL_Counter1_out1),
                                                                                  .dout(Simple_Dual_Port_RAM_out1)
                                                                                  );

  assign vMaxC = Simple_Dual_Port_RAM_out1;

  dvbs2hdlTransmitterCore_SimpleDualPortRAM_singlebit #(.AddrWidth(3),
                                                        .DataWidth(1)
                                                        )
                                                      u_Simple_Dual_Port_RAM2 (.clk(clk),
                                                                               .enb(enb),
                                                                               .wr_din(modcodis12),
                                                                               .wr_addr(HDL_Counter_out1),
                                                                               .wr_en(push),
                                                                               .rd_addr(HDL_Counter1_out1),
                                                                               .dout(Simple_Dual_Port_RAM2_out1)
                                                                               );

  assign vMODCODis12 = Simple_Dual_Port_RAM2_out1;

endmodule  // dvbs2hdlTransmitterCore_FIFO_3_Variables

