// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_MATLAB_Function.v
// Created: 2024-01-10 13:49:57
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_MATLAB_Function
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/BB Frame Generator/BB Header and Data CRC Generator/Data Field 
// Generator/Packetized Streams/MATLAB Functio
// Hierarchy Level: 7
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_MATLAB_Function
          (clk,
           reset,
           enb,
           pktEndIn,
           frameEndIn,
           frameEndOut);


  input   clk;
  input   reset;
  input   enb;
  input   pktEndIn;
  input   frameEndIn;
  output  frameEndOut;


  reg  frameEndOut_1;
  reg  frameEnded;
  reg  frameEnded_next;
  reg  frameEnded_temp;


  always @(posedge clk or posedge reset)
    begin : MATLAB_Function_process
      if (reset == 1'b1) begin
        frameEnded <= 1'b0;
      end
      else begin
        if (enb) begin
          frameEnded <= frameEnded_next;
        end
      end
    end

  always @(frameEndIn, frameEnded, pktEndIn) begin
    frameEnded_temp = frameEnded;
    if (frameEndIn) begin
      frameEnded_temp = 1'b1;
    end
    if (pktEndIn && frameEnded_temp) begin
      frameEndOut_1 = 1'b1;
      frameEnded_temp = 1'b0;
    end
    else begin
      frameEndOut_1 = 1'b0;
    end
    frameEnded_next = frameEnded_temp;
  end



  assign frameEndOut = frameEndOut_1;

endmodule  // dvbs2hdlTransmitterCore_MATLAB_Function

