// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_MODCOD_Source_Coder.v
// Created: 2024-01-10 13:49:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_MODCOD_Source_Coder
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/MODCOD Source Coder
// Hierarchy Level: 3
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_MODCOD_Source_Coder
          (clk,
           reset,
           enb,
           dataIn,
           startIn,
           endIn,
           validIn,
           MODCODIn,
           FECFrameIn,
           dataOut,
           startOut,
           endOut,
           validOut,
           modIdx,
           codeRateIdx,
           FECFrame,
           MODCOD);


  input   clk;
  input   reset;
  input   enb;
  input   dataIn;
  input   startIn;
  input   endIn;
  input   validIn;
  input   [4:0] MODCODIn;  // ufix5
  input   FECFrameIn;
  output  dataOut;
  output  startOut;
  output  endOut;
  output  validOut;
  output  [1:0] modIdx;  // ufix2
  output  [3:0] codeRateIdx;  // ufix4
  output  FECFrame;
  output  [4:0] MODCOD;  // ufix5


  reg  Delay7_out1;
  reg  Delay8_out1;
  reg  Delay14_out1;
  reg  Delay15_out1;
  reg [4:0] Unit_Delay_Enabled_Synchronous_out1;  // ufix5
  wire [4:0] Unit_Delay_Enabled_Synchronous_ectrl;  // ufix5
  wire [1:0] modIdx_1;  // ufix2
  wire [3:0] codIdx;  // ufix4
  reg  Delay16_out1;


  always @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= dataIn;
        end
      end
    end



  assign dataOut = Delay7_out1;

  always @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay8_out1 <= startIn;
        end
      end
    end



  assign startOut = Delay8_out1;

  always @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay14_out1 <= endIn;
        end
      end
    end



  assign endOut = Delay14_out1;

  always @(posedge clk or posedge reset)
    begin : Delay15_process
      if (reset == 1'b1) begin
        Delay15_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay15_out1 <= validIn;
        end
      end
    end



  assign validOut = Delay15_out1;

  assign Unit_Delay_Enabled_Synchronous_ectrl = (startIn == 1'b0 ? Unit_Delay_Enabled_Synchronous_out1 :
              MODCODIn);



  always @(posedge clk or posedge reset)
    begin : Unit_Delay_Enabled_Synchronous_lowered_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous_out1 <= 5'b00000;
      end
      else begin
        if (enb) begin
          Unit_Delay_Enabled_Synchronous_out1 <= Unit_Delay_Enabled_Synchronous_ectrl;
        end
      end
    end



  dvbs2hdlTransmitterCore_convertMODCOD u_convertMODCOD (.modcod(Unit_Delay_Enabled_Synchronous_out1),  // ufix5
                                                         .modIdx(modIdx_1),  // ufix2
                                                         .codIdx(codIdx)  // ufix4
                                                         );

  assign modIdx = modIdx_1;

  assign codeRateIdx = codIdx;

  always @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay16_out1 <= FECFrameIn;
        end
      end
    end



  assign FECFrame = Delay16_out1;

  assign MODCOD = Unit_Delay_Enabled_Synchronous_out1;

endmodule  // dvbs2hdlTransmitterCore_MODCOD_Source_Coder

