// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_For_Each_Subsystem1.v
// Created: 2024-01-10 13:49:59
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_For_Each_Subsystem1
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/PL Frame Generator/PL Header Generator/PL Header Bits Generator/PLSC 
// Generator/Bi Orthogonal Coding (32,6)/Integer to Bit Convertor/For Each Subsystem
// Hierarchy Level: 9
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_For_Each_Subsystem1
          (In1,
           Out1_0,
           Out1_1);


  input   [7:0] In1;  // uint8
  output  [3:0] Out1_0;  // ufix4
  output  [3:0] Out1_1;  // ufix4


  wire [3:0] Extract_Bits2_out1;  // ufix4
  wire [3:0] Extract_Bits3_out1;  // ufix4


  assign Extract_Bits2_out1 = In1[7:4];



  assign Out1_0 = Extract_Bits2_out1;

  assign Extract_Bits3_out1 = In1[3:0];



  assign Out1_1 = Extract_Bits3_out1;

endmodule  // dvbs2hdlTransmitterCore_For_Each_Subsystem1

