// -------------------------------------------------------------
// 
// File Name: F:\FileFolder\DVB\dvbs2_tx_new\hdlsrc\dvbs2hdlTransmitter\dvbs2hdlTransmitterCore\dvbs2hdlTransmitterCore_Input_RAM.v
// Created: 2024-01-10 13:49:58
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: dvbs2hdlTransmitterCore_Input_RAM
// Source Path: dvbs2hdlTransmitterCore/DVB-S2 Tx/FEC Encoder/DVB-S2 LDPC Encoder/Input RAM
// Hierarchy Level: 5
// Model version: 4.5
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dvbs2hdlTransmitterCore_Input_RAM
          (clk,
           enb,
           iwr_data,
           iwr_addr,
           iwr_enb,
           ird_addr,
           ird_data);


  input   clk;
  input   enb;
  input   iwr_data;
  input   [7:0] iwr_addr;  // uint8
  input   iwr_enb;
  input   [7:0] ird_addr;  // uint8
  output  ird_data;


  wire Simple_Dual_Port_RAM_out1;


  dvbs2hdlTransmitterCore_SimpleDualPortRAM_singlebit #(.AddrWidth(8),
                                                        .DataWidth(1)
                                                        )
                                                      u_Simple_Dual_Port_RAM (.clk(clk),
                                                                              .enb(enb),
                                                                              .wr_din(iwr_data),
                                                                              .wr_addr(iwr_addr),
                                                                              .wr_en(iwr_enb),
                                                                              .rd_addr(ird_addr),
                                                                              .dout(Simple_Dual_Port_RAM_out1)
                                                                              );

  assign ird_data = Simple_Dual_Port_RAM_out1;

endmodule  // dvbs2hdlTransmitterCore_Input_RAM

